### ISSUE TITLE
有没有可能直接让mutate支持一些特殊命令呢

### ISSUE THREAD

**Issue by panxiaoguang** [shenwei356/csvtk#102]
作者您好，假设有一个csv文件，其中有一列是DNA序列，我想筛选特定条件后把这部分序列反向互补，这个用CSVtk的mutate功能实现起来好想很复杂，需要提取两列去掉header然后转成fasta用seqkit处理然后再转回来，有没有可能直接让mutate支持一些特殊命令呢

**Comment by shenwei356** [comment]
不支持呢。

把序列那列提取出来，csvtk mutate 复制成2列，seqkit fx2tab转fasta，求互补序列，tab2fx转为表格格式；然后csvtk join添加到csv中去。

**Comment by panxiaoguang** [comment]
> 不支持呢。
> 
> 把序列那列提取出来，csvtk mutate 复制成2列，seqkit fx2tab转fasta，求互补序列，tab2fx转为表格格式；然后csvtk join添加到csv中去。

嗯嗯，好的感谢回复
