### ISSUE TITLE
csv2json handling of empty fields

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#104]
csv2json converts empty fields to `""`. This will confuse downstream processes, which may try to create a broken number, date, or relation to another node.

It is crucial that empty fields are emitted as `null`, or the field omitted altogether.

https://csvkit.readthedocs.io/en/latest/scripts/csvjson.html seems to handle this, as it has this option:
`  --blanks: Do not convert "", "na", "n/a", "none", "null", "." to NULL.`

**Comment by shenwei356** [comment]
Hi @VladimirAlexiev , it's supported now. Two options are added:

```
  -b, --blanks              do not convert "", "na", "n/a", "none", "null", "." to null
  -n, --parse-num strings   parse numeric values for nth column(s), multiple values are supported and "a"/"all" for all columns
```

<details>
<summary>USAGE</summary>


```text
convert CSV to JSON format

Usage:
  csvtk csv2json [flags]

Flags:
  -b, --blanks              do not convert "", "na", "n/a", "none", "null", "." to null
  -h, --help                help for csv2json
  -i, --indent string       indent. if given blank, output json in one line. (default "  ")
  -k, --key string          output json as an array of objects keyed by a given filed rather than as a list. e.g -k 1 or -k columnA
  -n, --parse-num strings   parse numeric values for nth column(s), multiple values are supported and "a"/"all" for all columns

```

Examples

- test data

        $ cat testdata/data4json.csv 
        ID,room,name,status
        3,G13,Simon,true
        5,103,Anna,TRUE
        1e-3,2,,N/A

- default operation

        $ cat testdata/data4json.csv | csvtk csv2json
        [
          {
            "ID": "3",
            "room": "G13",
            "name": "Simon",
            "status": true
          },
          {
            "ID": "5",
            "room": "103",
            "name": "Anna",
            "status": true
          },
          {
            "ID": "1e-3",
            "room": "2",
            "name": null,
            "status": null
          }
        ]

- change indent

        $ cat testdata/data4json.csv | csvtk csv2json -i ""
        [{"ID":"3","room":"G13","name":"Simon","status":true},{"ID":"5","room":"103","name":"Anna","status":true},{"ID":"1e-3","room":"2","name":null,"status":null}]

- output json as an array of objects keyed by a given filed rather than as a list.

        $ cat testdata/data4json.csv | csvtk csv2json -k ID
        {
          "3": {
            "ID": "3",
            "room": "G13",
            "name": "Simon",
            "status": true
          },
          "5": {
            "ID": "5",
            "room": "103",
            "name": "Anna",
            "status": true
          },
          "1e-3": {
            "ID": "1e-3",
            "room": "2",
            "name": null,
            "status": null
          }
        }

- for CSV without header row

        $ cat testdata/data4json.csv | csvtk csv2json -H
        [
          [
            "ID",
            "room",
            "name",
            "status"
          ],
          [
            "3",
            "G13",
            "Simon",
            "true"
          ],
          [
            "5",
            "103",
            "Anna",
            "TRUE"
          ],
          [
            "1e-3",
            "2",
            "",
            "N/A"
          ]
        ]

- parse numeric values.

        # cat testdata/data4json.csv | csvtk csv2json -n all    # for all columns
        # cat testdata/data4json.csv | csvtk csv2json -n 1,2    # for multiple columns
        $ cat testdata/data4json.csv | csvtk csv2json -n 1      # for single column
        [
          {
            "ID": 3,
            "room": "G13",
            "name": "Simon",
            "status": true
          },
          {
            "ID": 5,
            "room": "103",
            "name": "Anna",
            "status": true
          },
          {
            "ID": 1e-3,
            "room": "2",
            "name": null,
            "status": null
          }
        ]

- do not convert "", "na", "n/a", "none", "null", "." to null (just like csvjon --blanks in csvkit)

        $ cat testdata/data4json.csv | csvtk csv2json --blanks
        [
          {
            "ID": "3",
            "room": "G13",
            "name": "Simon",
            "status": true
          },
          {
            "ID": "5",
            "room": "103",
            "name": "Anna",
            "status": true
          },
          {
            "ID": "1e-3",
            "room": "2",
            "name": "",
            "status": ""
          }
        ]
        

</details>

**Comment by VladimirAlexiev** [comment]
Thanks a lot!!
