### ISSUE TITLE
Feature request new flag: csvtk stats -c for count entries

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#105]
Hi,

There already be a better way of doing this, but I would like to have a shortened way of finding the number of entries (rows) for a file, so that what's returned is simply the number back.

E.g.:

```
seq 1 10 | csvtk stats
file   num_cols   num_rows
-             1          9
```
It would be a clean way (similar to `samtools view -c` or `grep -c`) to get:

```
seq 1 10 | csvtk stats -c
9
```
Or:

```
seq 1 10 | csvtk stats -H -c
10
```

So that one can rely on the value back to be the rows. Thanks in advance!

**Comment by shenwei356** [comment]
I just added new flags recently:

    csvtk dim --rows --no-file  

But it seems too verbose……


csvtk stats is alias of dim.

**Comment by avilella** [comment]
Cool. Is that in a beta release?
I am running 0.20.0 and I get:

unknown flag: --rows

**Comment by shenwei356** [comment]
yes, but you have to compile by yourself cause I can't access my PC for few days.

**Comment by shenwei356** [comment]
[csvtk_darwin_386.tar.gz](https://github.com/shenwei356/csvtk/files/4742267/csvtk_darwin_386.tar.gz)
[csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4742268/csvtk_darwin_amd64.tar.gz)
[csvtk_linux_386.tar.gz](https://github.com/shenwei356/csvtk/files/4742269/csvtk_linux_386.tar.gz)
[csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4742270/csvtk_linux_amd64.tar.gz)
[csvtk_windows_386.exe.tar.gz](https://github.com/shenwei356/csvtk/files/4742272/csvtk_windows_386.exe.tar.gz)
[csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/4742273/csvtk_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
we can learn from R, providing `nrow`, `ncol`, and `dim`, and optionally showing file name (`-n`).

**Comment by shenwei356** [comment]
> we can learn from R, providing `nrow`, `ncol`, and `dim`, and optionally showing file name (`-n`).

```
$ seq 1 10 | csvtk nrow
9

$ seq 1 10 | csvtk nrow -H
10

$ seq 1 10 | csvtk ncol
1
```
