### ISSUE TITLE
Feature request: csvtk summary -g -field -f field:max

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#107]
Here is a feature request of something I want to do, which may already be available in a different way:

Say we have done a `csvtk join` of a table A with lots of columns and a table B with a final column being a frequency field.

What we want is to summarise or collapse the result of the `csvtk join` so that all the columns in table A now are shown with the result of applying the max operation on the frequency column in table B. E.g.:
```
csvtk cut -t -f this,table,has,lots,of,columns,which,we,want,to,retain tableA.tsv \
| csvtk join -t -f "1;1" - <(csvtk freq -t -f this,foo  tableB.csv) \
| csvtk summary -t -g -frequency -f frequency:max
```
Notice the `-g -frequency` above.

Currently, the grouping `-g` seems to need explicit column enumeration, e.g. this works:
```
csvtk summary -t -g this,table,has,lots,of,columns,which,we,want,to,retain,foo  -f frequency:max
```
But if `csvtk summary` accepted the `-frequency` (all except frequency field), then no matter what combination of fields comes from the earlier join, the max operation would return only the max frequency entry with all the other columns preserved.

Looking forward to hearing from you. Thanks in advance,

**Comment by avilella** [comment]
In retrospect, I misunderstood how `csvtk summary -g field1 -f field2:max` works, but I found an alternative way here:

```
csvtk freq -t -f 1,2 file.tsv | csvtk sort -t -k 1:N -k 3:rn | csvtk summary -t -g 1 -f 2:collapse -f 3:collapse \
       | csvtk sep -t -s ';' -f 2 -n foo --drop --remove -N 1 \
       | csvtk sep -t -s ';' -f 2 -n foo_count --drop --remove -N 1
```

**Comment by shenwei356** [comment]
I'm a little dizzy ~ But I think I understand what you need.

Since frequencies are counted with keys of "this,foo" in tableB.csv, and when the frequency table joined to tableA with  index "this" in tableA and "this" in tableB, this makes every combination of "this,table,has,lots,of,columns,which,we,want,to,retain,foo" having only ONE frequency, so don't need compute the maximum value of the ONLY ONE frequency.

Correct me if I misunderstood.

**Comment by shenwei356** [comment]
```
$ cat tableA.csv 
this,table,has,lots
1,a,b,c
1,a,b,c
1,a,b,e
2,d,e,f
3,g,h,i

$ cat tableB.csv 
this,foo,value
1,11,A
1,11,e
2,22,B
1,1,B
1,22,C
2,22,D
3,11,E
4,22,e

$ csvtk cut -f this,table,has,lots tableA.csv \
    | csvtk join -f "1;1" - <(csvtk freq -f this,foo tableB.csv) --left-join  
this,table,has,lots,foo,frequency
1,a,b,c,11,2
1,a,b,c,1,1
1,a,b,c,22,1
1,a,b,c,11,2
1,a,b,c,1,1
1,a,b,c,22,1
1,a,b,e,11,2
1,a,b,e,1,1
1,a,b,e,22,1
2,d,e,f,22,2
3,g,h,i,11,1


$ csvtk cut -f this,table,has,lots tableA.csv \
        | csvtk join -f "1;1" - <(csvtk freq -f this,foo tableB.csv) --left-join  \
        | csvtk sort -k this,table,has,lots,foo -k frequency:nr
1,a,b,c,1,1
1,a,b,c,1,1
1,a,b,c,11,2
1,a,b,c,11,2
1,a,b,c,22,1
1,a,b,c,22,1
1,a,b,e,1,1
1,a,b,e,11,2
1,a,b,e,22,1
2,d,e,f,22,2
3,g,h,i,11,1

$ csvtk cut -f this,table,has,lots tableA.csv \
        | csvtk join -f "1;1" - <(csvtk freq -f this,foo tableB.csv) --left-join  \
        | csvtk uniq -f -frequency
this,table,has,lots,foo,frequency
1,a,b,c,11,2
1,a,b,c,1,1
1,a,b,c,22,1
1,a,b,e,11,2
1,a,b,e,1,1
1,a,b,e,22,1
2,d,e,f,22,2
3,g,h,i,11,1
```
