### ISSUE TITLE
Consistent reports for `dim` 

### ISSUE THREAD

**Issue by wavefancy** [shenwei356/csvtk#108]
Hi @shenwei356 ,

Can you please improve the the `dim`  reports to make it has a consistent output format if the input file is empty. Now, it reported as '[ERRO]', which is not convenient if want to check a list of files.

For example:
```
csvtk dim -t results/rareids.*.txt.gz 
[ERRO] xopen: no content
```

Report as `0 0` probably is better. As the empty file probably is not an `ERROR`, which may be true results. The 'ERRO' also interrupted the checking for other files.

Best regards
Wallace

**Comment by shenwei356** [comment]
ok.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5100327/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5100328/csvtk_linux_amd64.tar.gz)

**Comment by wavefancy** [comment]
Now, works fantastic for me.
Thank you very much for your great help.

Best regards
Wallace
