### ISSUE TITLE
how to do a join on field string match

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#111]
Is there a way of doing a `csvtk join` on field string match?

E.g. If we had a couple of fields to do a join, but one of them is a string match of a substring against another full string:

# a.csv
```
field1,field2
1,TAGCATG
2,TAGCTAG
3,ATATATA
4,CGCGCG
5,CGATCA
```

# b.csv
```
field1,field2
1,XXXTAGCATGXXX
2,YYYTAGCTAGYYY
3,ZZZATATATAZZZ
4,XXXCGCGCGXXX
5,XXXCGATCAXXX
```
Is there a way that something like this join would work on the basis of field2 in a being a substring in field2 of b?
```
csvtk join -f "1,2;1,2" a.csv b.csv
```

Thanks in advance.

**Comment by shenwei356** [comment]
using `mutate` to extract the substring before joining.
