### ISSUE TITLE
feature request: limit precision of floats in `pretty`

### ISSUE THREAD

**Issue by ctb** [shenwei356/csvtk#112]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

I have a CSV with floating point numbers in it, and it would be great to limit them to ~3 signif digits -- here's what it looks like currently. I can't find a flag to do that tho!

```
csvtk cut twofoo_k31_r1_search_oh0/results.csv  -f best_containment,cdbg_min_overhead,catlas_min_overhead | csvtk pretty
best_containment     cdbg_min_overhead        catlas_min_overhead
0.9999198549640733   1.4814505299984235e-05   0.005855691531263713
0.7734263551896505   0.07683380394531308      0.2544437040336933
0.9478159807721671   0.02152625515812585      0.17919530049961052
```

**Comment by shenwei356** [comment]
Added a new command `round`, [v0.21.0rc1](https://github.com/shenwei356/csvtk/releases/tag/v0.21.0rc1)

You can use

    csvtk cut twofoo_k31_r1_search_oh0/results.csv  -f best_containment,cdbg_min_overhead,catlas_min_overhead \
        | csvtk round -a \
        | csvtk pretty

Usage:

```text
round float to n decimal places

Usage:
  csvtk round [flags]

Flags:
  -a, --all-fields          all fields, overides -f/--fields
  -n, --decimal-width int   limit floats to N decimal points (default 2)
  -f, --fields string       select only these fields. e.g -f 1,2 or -f columnA,columnB (default "1")
  -F, --fuzzy-fields        using fuzzy fields, e.g., -F -f "*name" or -F -f "id123*"
  -h, --help                help for round

```

Examples:

    $ cat testdata/floats.csv  | csvtk pretty
    a                        b
    0.12345                  abc
    NA                       0.9999198549640733
    12.3                     e3
    1.4814505299984235e-05   -3.1415926E05

    # one or more fields
    $ cat testdata/floats.csv | csvtk round -n 2 -f b | csvtk pretty 
    a                        b
    0.12345                  abc
    NA                       1.00
    12.3                     e3
    1.4814505299984235e-05   -3.14E05

    # all fields
    $ cat testdata/floats.csv | csvtk round -n 2 -a | csvtk pretty 
    a          b
    0.12       abc
    NA         1.00
    12.30      e3
    1.48e-05   -3.14E05

**Comment by ctb** [comment]
wow, thanks!
