### ISSUE TITLE
output-delimiter does not work if input is not CSV

### ISSUE THREAD

**Issue by tolot27** [shenwei356/csvtk#114]
I'm using csvtk v0.21 on Windows and Linux and tried do set a different output separator, but it does not work if the input is not comma-separated.

Works with CSV:
```
echo -e "col1,col2" | csvtk -D ";" cut -f 1,2
col1;col2
``` 

Does not work if non-CSV:
```
echo -e "col1\tcol2" | csvtk -t -D ";" cut -f 1,2
col1	col2
```

**Comment by shenwei356** [comment]
-t, --tabs                   specifies that the input CSV file is delimited with tabs. Overrides "-d" and "-D"

You can convert TSV to CSV before cuting.

**Comment by shenwei356** [comment]
$ echo -e "col1\tcol2" | csvtk tab2csv | csvtk  -D ";" cut -f 1,2
col1;col2

**Comment by tolot27** [comment]
I've overlooked that `-t, --tabs` overrides `-D`. It is obvious that `-d` gets overwritten and that the output separator gets a suitable default (tab), if no other output separator is specified. I wish `-D` can be used in combination with any input separator. That would increase the flexibility quite a lot.
My example above was just to provide a reproducable example. My real use case is to read tsv with empty fields: 
```
csvtk -t ... | csvtk -t del-header | tr $'\t' $'\a' | while IFS=$'\a' read -r ... 
```
I thought I could save one more process by removing the `tr`.

**Comment by shenwei356** [comment]
It's supported now. Global flag `-t` does not overide `-D` anymore.


- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5475241/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5475246/csvtk_linux_amd64.tar.gz)

**Comment by tolot27** [comment]
Thank you!

**Comment by ammaraziz** [comment]
@shenwei356 I think there's been a reversion of this in the latest version of csvtk on macos arm:

```
% cat test.tsv
f1      f2      f3      f4      f5
foo     bar     xyz     1       0
foo     bar2    xyz     1.5     -1
```

```
% csvtk -t rename test.tsv -f "f1" -n "b" -D "," > test.cs
% cat test.tsv
b       f2      f3      f4      f5
foo     bar     xyz     1       0
foo     bar2    xyz     1.5     -1
```

oddly enough this works:
```
% csvtk -t rename test.tsv -f "f1" -n "b" -D ";" > test.csv
% cat test.csv
b;f2;f3;f4;f5
foo;bar;xyz;1;0
foo;bar2;xyz;1.5;-1
```

details:
- csvtk v0.30.0
- installed on macos arm
- using rosetta emulation

**Comment by shenwei356** [comment]
Oh, just check the previous commit.   `-t` overwrites `-D` when it's ",".
So you have to use `csvtk tab2csv`.

**Comment by ammaraziz** [comment]
Thanks that works nicely. Actually like it better as it's very clear what's happening when there's a large chain of pipes.
