### ISSUE TITLE
csvtk corr function don‘’t work when file doesn't have header.

### ISSUE THREAD

**Issue by flystar233** [shenwei356/csvtk#115]
`>cat test.txt`
`col1    col2    col3`
`1       2       1`
`1       1       1`
`2       1       4`
`5       8       1`
`>cat no_h_test.txt`
`1       2       1`
`1       1       1`
`2       1       4`
`5       8       1`
![image](https://user-images.githubusercontent.com/20431495/97851896-f3bfc880-1d30-11eb-8667-bad0e6602470.png)

**Comment by shenwei356** [comment]
@bsipos please help, I tried to fixed this bug, but failed :cry:

**Comment by cgjosephlee** [comment]
Hi there, is this fix merged into release? I still have same issue with v0.23.
