### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by dawnmy** [shenwei356/csvtk#12]
Could you submit this CLI tool to Homebrew so it could be convinently installed and upgraded on MacOS with brew.

**Comment by shenwei356** [comment]
Any contributions are welcome.

**Comment by shenwei356** [comment]
- Found a similar binary tool: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-clean.rb
- http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html
- csvtk for bioconda: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/csvtk/meta.yaml
- linuxbrew: http://linuxbrew.sh/

**Comment by shenwei356** [comment]
I give up. It's to complicated and not necessary.
