### ISSUE TITLE
replace does not support global group matching 

### ISSUE THREAD

**Issue by tolot27** [shenwei356/csvtk#121]
I'm using the `replace` command of csvtk v0.22. Unfortunately, I'm not able to get repeated group matches.

`echo "g1|g2|g3" | csvtk replace -H -f 1 -p '([^|]+)*' -r '$1'` returns `g1|g2|g3` instead of `g1` and `echo "g1|g2|g3" | csvtk replace -H -f 1 -p '([^|]+)' -r '$2'` returns `||`.

If I test the same regex using Golang (RE2) at https://regex101.com/r/uASYPO/2 and enabling the global flag, it works.

Is it possible to get csvtk also matching globally?

**Comment by shenwei356** [comment]
It seems golang does not support this. Ingoring cases is set by `(?i)`, but there's no flag like `(?g)` for this. It's weird.

**Comment by shenwei356** [comment]
```
$ echo "g1|g2|g3" | csvtk replace -H -f 1 -p '([^|]+)*' -r '($1)'
(g1)|(g2)|(g3)
```
It matches all groups, the problem may be related to the [Regexp.ReplaceAllString](https://golang.org/pkg/regexp/#Regexp.ReplaceAllString) method, where it finds a match (`g1`, `g2` and `g3) and replaces with `$1`  (`g1`, `g2` and `g3`).
