### ISSUE TITLE
add option to join by disjunction

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#125]
I have a sublist list of [IANA lang tags](https://docs.google.com/spreadsheets/d/1M1yv9aBUmc-NyCJX69vOLUmH2uIglSwmDwgRgByI1AI/edit) (those with `Suppress-Script=Latn`): 80 of them have ISO alpha2 codes but 10 have alpha3.

I want to join to a master list of ISO codes, where all have alpha3 and some have alpha2.

This fails because the number of join fields must be the same:
```
csvtk join -L -f "iana;iso2,iso3" IANA.csv ISO.csv
```

I am ok to split the IANA codes to two different columns `iso2,iso3` according to their length.
But the following doesn't add any info because it looks for *both* fields to match, whereas in the IANA file only *one* field is filled out in each row.
(Note: when there's no semicolon in `-f`, it uses the same fields for both files)
```
csvtk join -L -f "iso2,iso3" IANA.csv ISO.csv
```

So I thought maybe an option like this could be useful:
```
#  -X Join if any pair of fields matches (rather than all pairs of fields)

csvtk join -L -X -f "iso2,iso3" IANA.csv ISO.csv
```

**Comment by shenwei356** [comment]
Hmm, does the `??` in #129 work for this?

**Comment by VladimirAlexiev** [comment]
Yes, ?? will work to merge fields iso2 and iso3 to a single field .

I agree to cancel this issue since its usefulness is not very clear
