### ISSUE TITLE
genautocomplete should list bash_completion as a prerequisite

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#126]
I use cygwin bash and decided to try the autocompletion:
```
csvtk genautocomplete
[INFO] bash completion file for csvtk saved to C:\my\.bash_completion.d\csvtk.sh
```

I followed some example and added this to my bashrc:
```sh
test -f ~/.bash_completion.d/csvtk.sh && . ~/.bash_completion.d/csvtk.sh
```

However, when trying to complete a filename, this led to error `undefined function _get_comp_words_by_ref` (very disruptive).
I examined csvtk.sh and saw this:
```sh
# Homebrew on Macs have version 1.3 of bash-completion which doesn't include
# _init_completion. This is a very minimal version of that function.
__csvtk_init_completion()
{
    COMPREPLY=()
    _get_comp_words_by_ref "$@" cur prev words cword
}
```

From that comment I figured out that I need to also source `bash_completion`. Luckily it comes standard in cygwin bash, so I added an extra line and now everything is ok (plus I get extra completions for about 100 packages, nice!)

```sh
test -f /usr/share/bash-completion/bash_completion && . /usr/share/bash-completion/bash_completion # prereq for next row
test -f ~/.bash_completion.d/csvtk.sh && . ~/.bash_completion.d/csvtk.sh
```

-----

Please:
- Add that prerequisite to the doc: https://bioinf.shenwei.me/csvtk/#bash-completion
- `csvtk genautocomplete` should also print more instructions, eg

```
[INFO] bash_completion is a prerequisite for csvtk autocomplete, so source both of them in your bash profile, eg:
test -f /usr/share/bash-completion/bash_completion && . /usr/share/bash-completion/bash_completion
test -f ~/.bash_completion.d/csvtk.sh && . ~/.bash_completion.d/csvtk.sh
```

**Comment by shenwei356** [comment]
update the doc with simpler instructions:

    # generate completion shell
    csvtk genautocomplete --shell bash

    # configure if never did
    echo "for bcfile in ~/.bash_completion.d/* ; do source $bcfile; done" >> ~/.bash_completion
    echo "source ~/.bash_completion" >> ~/.bashrc

It also supports zsh, fish, and power shell. But I can't figure out how to configure for powershell. 

    $ csvtk genautocomplete --shell powershell --file csvtk.ps1

I failed many times to make it work.

- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5980705/csvtk_linux_amd64.tar.gz) 
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5980706/csvtk_darwin_amd64.tar.gz)
- [csvtk_windows_386.exe.tar.gz](https://github.com/shenwei356/csvtk/files/5980702/csvtk_windows_386.exe.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/5980701/csvtk_windows_amd64.exe.tar.gz)

**Comment by VladimirAlexiev** [comment]
But  does your instruction guarantee that `_get_comp_words_by_ref` exists and is loaded before ​`__csvtk_init_completion​`?

**Comment by shenwei356** [comment]
Let's tell users to install `bash-completion`.


    # generate completion shell
    csvtk genautocomplete --shell bash

    # configure if never did.
    # install bash-completion if the "complete" command is not found.
    echo "for bcfile in ~/.bash_completion.d/* ; do source \$bcfile; done" >> ~/.bash_completion
    echo "source ~/.bash_completion" >> ~/.bashrc
