### ISSUE TITLE
digits vs numbers

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#127]
Thanks for your excellent toolkit!
Your documentation is also very comprehensive and useful.

There is however one aspect that is confusing:
- `digits` are the symbols 0..9 (in the decimal system; eg in octal it's 0..7 and in hexadecimal 0..F).
- `numbers` are integers or floats that are made of digits

For example, if you have these:
```
123
456
```
that's 2 numbers but 6 digits.

Almost everywhere in the doc and program messages when you write "digits" you really mean "numbers".

Suggestions for rewording:
- all: "Do not mix using digital fields and column names" -> "Do not mix the use of field numbers and column names"
- "remember not mixing use digital fields and column names" -> "remember not to mix the use of field numbers and column names"
- "fail to parse digital field: f5, you may mix use digital fields and column names" -> "failed to parse f5 as a field number, maybe you are mixing the use of field numbers and column names?"
- "summary statistics of selected digital fields (groupby group fields)" ->
  - "summary statistics of selected numeric or text fields (with groupby by fields)"
- summary: "countn (count of digits)" -> "countn (count numeric values)"
- summary option `-i, --ignore-non-digits   ignore non-digital values` ->
  -  `-i, --ignore-non-numbers   ignore non-numeric values`
- `column 4 has non-digital data` -> `column 4 has non-numeric data`
- mutate2:
  - `-L, --digits int          number of digits after the dot (default 2)`: keep it but say "decimal dot"
  - `-s, --digits-as-string    treate digits as string to avoid converting big digits into scientific notation` ->
    -  `-s, --numeric-as-string    treat even numeric fields as strings to avoid converting big numbers into scientific notation`

THANKS!

**Comment by shenwei356** [comment]
Thank you very much! I'll correct them.

**Comment by VladimirAlexiev** [comment]
Not just `fix doc` but also fix command messages.
