### ISSUE TITLE
make documentation body wider

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#128]
Thanks for your very comprehensive documentation!
But could you please change the theme to allow 50% more width for the documentation body?
You have some quite wide command examples, and it's very inconvenient to have to scroll horizontally to read them.

Eg at https://bioinf.shenwei.me/csvtk/usage/#comb, I guess there's more at the end of the highlighted line, but I can't even see the scrollbar (it's below the bottom of the screen).
![image](https://user-images.githubusercontent.com/536250/106882127-11f9e380-66e7-11eb-8e74-8ffb05b98882.png)

On the other hand, there's a lot of wasted space on the left and right sides.

**Comment by shenwei356** [comment]
Oh sorry.

I've tried to edit the mkdocs theme, but didn't find the right place.

And I should at least wrapped the commands.

**Comment by VladimirAlexiev** [comment]
I haven't looked at the source but inspected with Chrome and I think you need to touch two places:
```css
// _base.scss#L84
.md-grid {
  // max-width: 61rem; // remove

// _sidebar.scss#L34
.md-sidebar {
  // width: 12.1rem; // remove or reduce
```

**Comment by shenwei356** [comment]
Thanks, it works!
