### ISSUE TITLE
mutate2: coalesce and ternary problems

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#129]
I'm trying to merge two cols: use the first one if filled, else the second one.
Sample data:
```
echo -e "one,two\na1,a2\n,b2\na2," |csvtk pretty
one   two
a1    a2
      b2
a2
```

I expected `??` (coalesce) to do this, eg:
```
$ echo -e "one,two\na1,a2\n,b2\na2," | csvtk mutate2 -n three -e '$one ?? $two'|csvtk pretty
one   two   three
a1    a2    a1
      b2
a2          a2
```
But why's the result in row2 empty?

Then I tried to use the conditional (ternary):
```
echo -e "one,two\na1,a2\n,b2\na2," | csvtk mutate2 -n three -e '$one!='' ? $one : $two'|csvtk pretty
[ERRO] Cannot transition token types from COMPARATOR [!=] to TERNARY [?]
[ERRO] xopen: no content
```
Hmmm? The first arg of TERNARY is a boolean, and COMPARATOR produces a boolean, so what's the problem?

I tried explicit parentheses, although COMPARATOR should bind more tightly than TERNARY, so that should not be necessary:
```
echo -e "one,two\na1,a2\n,b2\na2," | csvtk mutate2 -n three -e '($one!='') ? $one : $two'|csvtk pretty
one   two   three
a1    a2    a1
      b2
a2          a2
```
But again the result in row2 is empty.

**Comment by shenwei356** [comment]
```
$  echo -e "one,two\na1,a2\n,b2\na2,"\
    | csvtk mutate2 -n three -e '$one == "" ? $two : $one' \
    | csvtk pretty 
one   two   three
---   ---   -----
a1    a2    a1
      b2    b2
a2          a2
```

**Comment by shenwei356** [comment]
> echo -e "one,two\na1,a2\n,b2\na2," | csvtk mutate2 -n three -e '$one!='' ? $one : $two'|csvtk pretty

Two single-quotes rather than two double-quotes misused.

     echo -e "one,two\na1,a2\n,b2\na2," | csvtk mutate2 -n three -e '$one!="" ? $one : $two'|csvtk pretty

**Comment by shenwei356** [comment]
Ok, I know it. `??` only works for null/nil value, while the empty string is not. I add the detection of `??` and convert `""` to `nil` so it can work.

```
$ echo -e "one,two\na1,a2\n,b2\na2," \
    | csvtk mutate2 -n three -e '$one ?? $two' \
    | csvtk pretty
one   two   three
---   ---   -----
a1    a2    a1
      b2    b2
a2          a2
```

**Comment by shenwei356** [comment]
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/5982267/csvtk_windows_amd64.exe.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5982269/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/5982272/csvtk_darwin_amd64.tar.gz)
