### ISSUE TITLE
Support for separator declaration (used by Excel)

### ISSUE THREAD

**Issue by thunfischbrot** [shenwei356/csvtk#13]
In order to get Excel to always accept CSV files some of our legacy lab equipment adds a line such as

    sep=,

as a first line. Trying to manipulate them, e.g. with csvtk transpose results in

    [ERRO] read .\Testing.csv: The handle is invalid.

Would you consider catching this line, ignoring it and adding it to the resulting file if present? Could very well be a command-line option as well.

**Comment by shenwei356** [comment]
Does Excel support this format with leading line `seq=,`? Is this common?

It's not hard not implement, but still take some time.

**Comment by shenwei356** [comment]
I get it. It's a EXCEL specific feature. I'll add a global flag `--excel` to support this.

- http://superuser.com/questions/773644/what-is-the-sep-metadata-you-can-add-to-csvs
- http://superuser.com/questions/407082/easiest-way-to-open-csv-with-commas-in-excel/

**Comment by thunfischbrot** [comment]
That would be amazing. Thank you for considering it!

**Comment by shenwei356** [comment]
I've added seamless support for data with meta line of separator declaration used by MS Excel. 

See this [pre-release](https://github.com/shenwei356/csvtk/releases/tag/v0.7.0-dev), please download and try it. Any feedback is welcome.

Enjoy it!

**Comment by thunfischbrot** [comment]
That's great! Tested it, it works for reading files with the separator line and writing the separator line into the resulting csv. Curiously though when using a file with separator it does not transpose larger files completely:
[Screenshot](http://i.imgur.com/FcX513h.png)

Here are the test files if you'd like to try them:
https://we.tl/WnLhln5lHC

Thank you for your effort, this is going to save quite some time over the coming years!

**Comment by shenwei356** [comment]
Fixed it in [v0.7.0-dev1](https://github.com/shenwei356/csvtk/releases/tag/v0.7.0-dev1). 

Please test it.

**Comment by thunfischbrot** [comment]
Tested. Works well on small and large files.

Incredible turn-around time. Thank you so much!

**Comment by shenwei356** [comment]
Well, I just released the v0.7.0-dev2. Make sure it's the version you tested.

Formal version will be released only after add functional tests.

**Comment by thunfischbrot** [comment]
Was testing v0.7.0-dev1. Now downloaded v0.7.0-dev2, also works as advertised!
