### ISSUE TITLE
renaming tsv header, wrong number of fields

### ISSUE THREAD

**Issue by cchurchw** [shenwei356/csvtk#134]
I am having an issue renaming a tsv header. I was using version 0.19.1 without a problem but I've updated to 0.22.0 and the same command I was using before gives the below error. I made an example to the issue I'm having:

```bash
(csvtk) -bash-4.2$ cat example.tsv
a       b       c
d       e       f
g       h       i
j       k       l
m       n       o
(csvtk) -bash-4.2$ csvtk cat -t example.tsv | csvtk rename -t -f 1,2,3 -n "A,B,C" > example.header
Streaming file: example.tsv
[ERRO] record on line 2: wrong number of fields
```

**Comment by shenwei356** [comment]
Hi, It's a bug of `csvtk cat`, a recent change wrongly output the progress bar to STDOUT, It's fixed now.

Actually, you can avoid using `csvtk cat`:

    csvtk rename -t -f 1,2,3 -n "A,B,C" example.tsv

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6096536/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6096537/csvtk_linux_amd64.tar.gz)
