### ISSUE TITLE
can't grep for comma in a field

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#135]
I want to search for comma or semicolon in a TSV.
Unfortunately the comma is interpreted as separator between **two** regexps, rather than part of regex
```
csvtk grep -t -f field -r -p '[;,]' file.tsv 
[ERRO] error parsing regexp: missing closing ]: `[;`
```

As the help says:
- `-p, --pattern strings`       query pattern (**multiple values supported**)

Please change the behavior to NOT interpret comma as a separator.
If someone wants to give multiple patterns, they should use `-p` multiple times.
So all of these should find the same rows (having comma or semicolon):
```
csvtk grep -t -f field -r -p '[;,]'     file.tsv 
csvtk grep -t -f field -r -p ';' -p ',' file.tsv 
csvtk grep -t -f field    -p ';' -p ',' file.tsv 
```

**Comment by shenwei356** [comment]
The argument parser treats patterns as CSV lines. I add a note:

    Attention: use double quotation marks for patterns containing comma, e.g., -p '"A{2,}"'

You can use 

```
csvtk grep -t -f field -r -p '"[;,]"'     file.tsv 
csvtk grep -t -f field -r -p ';' -p '","' file.tsv 
csvtk grep -t -f field    -p ';' -p '","' file.tsv 
```

**Comment by VladimirAlexiev** [comment]
- IMHO this is highly non-intuitive. Is there a chance for you to change this parsing?
- Can you clarify whether the regex (`-r`) is anchored, or one needs to use `^...$` to match the whole field?

**Comment by shenwei356** [comment]
> IMHO this is highly non-intuitive. Is there a chance for you to change this parsing?

I'm afraid it's hard to change the infrastructure. But I can detect this special case and show a warning message.

> Can you clarify whether the regex (-r) is anchored, or one needs to use ^...$ to match the whole field?

By default, the pattern tries to match the whole field, and the `-r` is for partial matching.
