### ISSUE TITLE
the separator of output is still multiple spaces rather than tabs when run "cat file|csvtk pretty -D $'\t' -t "

### ISSUE THREAD

**Issue by zhaoxvwahaha** [shenwei356/csvtk#136]
I used the Toolkit and csvtk to show the taxnomy lineage, and wanna show the output in excel, but the separator of output file is still multiple spaces rather than tabs when run "cat file|csvtk pretty -D $'\t' -t ", so I could't separate columns in excel based on tab, did I set something wrong?

**Comment by shenwei356** [comment]
Do not use `pretty` if you want to save the result to file, `pretty` is just for printing readable text in the terminal

**Comment by shenwei356** [comment]
BTW, you can use `csv2xlsx` to directly convert content to `.xlsx` file.

    seq 10 | csvtk csv2xlsx -H -t -o a.xlsx

**Comment by zhaoxvwahaha** [comment]
Got it, thank you very much.
