### ISSUE TITLE
feature request: new command csv2rst

### ISSUE THREAD

**Issue by peterjc** [shenwei356/csvtk#137]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

### Description

I would like to be able to turn CSV or TSV files etc into reStructuredText (RST) tables.
See https://docs.anaconda.com/restructuredtext/detailed/#tables or https://docutils.sourceforge.io/docs/user/rst/quickref.html#tables

### Example

Consider a simple input table, I personally prefer tabs:

```
$ csvtk tab2csv names.tsv 
id,first_name,last_name,username
11,Rob,Pike,rob
2,Ken,Thompson,ken
4,Robert,Griesemer,gri
1,Robert,Thompson,abc
NA,Robert,Abel,123
```

You already support markdown output:

```
$ csvtk csv2md -t names.tsv 
id |first_name|last_name|username
:--|:---------|:--------|:-------
11 |Rob       |Pike     |rob
2  |Ken       |Thompson |ken
4  |Robert    |Griesemer|gri
1  |Robert    |Thompson |abc
NA |Robert    |Abel     |123
```

Rendered here with GitHub,

id |first_name|last_name|username
:--|:---------|:--------|:-------
11 |Rob       |Pike     |rob
2  |Ken       |Thompson |ken
4  |Robert    |Griesemer|gri
1  |Robert    |Thompson |abc
NA |Robert    |Abel     |123

My desired functionality is just the simplest RST table markup:

```
$ csvtk csv2rst-t names.tsv 
== ========== ========= ========
id first_name last_name username
== ========== ========= ========
11 Rob        Pike      rob
2  Ken        Thompson  ken
4  Robert     Griesemer gri
1  Robert     Thompson  abc
NA Robert     Abel      123
== ========== ========= ========
```

That is close to the existing pretty output:

```
$ csvtk pretty -t names.tsv -s " "
...
```

I've not looked at the rest of csvtk to say if there is value in making an RST grid table, it is more verbose but allows more rich entries:

```rst
+----+------------+-----------+----------+
| id | first_name | last_name | username |
+====+============+===========+==========+
| 11 | Rob        | Pike      | rob      |
+----+------------+-----------+----------+
| 2  | Ken        | Thompson  | ken      |
+----+------------+-----------+----------+
| 4  | Robert     | Griesemer | gri      |
+----+------------+-----------+----------+
| 1  | Robert     | Thompson  | abc      |
+----+------------+-----------+----------+
| NA | Robert     | Abel      | 123      |
+----+------------+-----------+----------+
```

**Comment by shenwei356** [comment]
Here it is. 

- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6275753/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6275752/csvtk_darwin_amd64.tar.gz)

But it can't handle unicode (utf-f8) well, tested at http://rst.aaroniles.net/

Usage


```text
convert CSV to readable aligned table

Attention:

  1. row span is not supported.

Usage:
  csvtk csv2rst [flags]

Flags:
  -k, --cross string               charactor of cross (default "+")
  -s, --header string              charactor of separator between header row and data rowws (default "=")
  -h, --help                       help for csv2rst
  -b, --horizontal-border string   charactor of horizontal border (default "-")
  -p, --padding string             charactor of padding (default " ")
  -B, --vertical-border string     charactor of vertical border (default "|")

```

Example

1. With header row

        $ csvtk csv2rst testdata/names.csv 
        +----+------------+-----------+----------+
        | id | first_name | last_name | username |
        +====+============+===========+==========+
        | 11 | Rob        | Pike      | rob      |
        +----+------------+-----------+----------+
        | 2  | Ken        | Thompson  | ken      |
        +----+------------+-----------+----------+
        | 4  | Robert     | Griesemer | gri      |
        +----+------------+-----------+----------+
        | 1  | Robert     | Thompson  | abc      |
        +----+------------+-----------+----------+
        | NA | Robert     | Abel      | 123      |
        +----+------------+-----------+----------+

1. No header row

        $ csvtk csv2rst -H -t  testdata/digitals.tsv 
        +---+-------+---+
        | 4 | 5     | 6 |
        +---+-------+---+
        | 1 | 2     | 3 |
        +---+-------+---+
        | 7 | 8     | 0 |
        +---+-------+---+
        | 8 | 1,000 | 4 |
        +---+-------+---+
        
1. Misc


        $ cat testdata/names.csv | head -n 1 | csvtk csv2rst 
        +----+------------+-----------+----------+
        | id | first_name | last_name | username |
        +====+============+===========+==========+
        
        $ cat testdata/names.csv | head -n 1 | csvtk csv2rst -H
        +----+------------+-----------+----------+
        | id | first_name | last_name | username |
        +----+------------+-----------+----------+
        
        $ echo | csvtk csv2rst -H
        [ERRO] xopen: no content
        
        $ echo "a" | csvtk csv2rst -H
        +---+
        | a |
        +---+
        
        # some online rst render reports error
        $ echo "沈伟" | csvtk csv2rst -H
        +--------+
        | 沈伟 |
        +--------+

**Comment by peterjc** [comment]
Wow - that was quick. Thank you.

The "rich" RST table syntax does seem more flexible, and will cope with single rows etc. So I understand why you might prefer that.

I was not aware of the RST table issue with unicode, it also happens on https://livesphinx.herokuapp.com/ which is another online test system for RST using Sphinx. Sometimes it works, e.g. emoji or a kanji:

```
+------------+
| Hello.     |
+----+-------+
| 😀 | Smile |
+----+-------+
```

```
+-----------+
| Hello.    |
+----+------+
| 金 | Gold |
+----+------+
```

I tried some Japanese hiragana, and like your example failed to get it to work regardless of the number of spaces (in case it was a length issue). I think this is probably a bug in the docutils library, perhaps the same thing this sphinx user was asking about: https://github.com/sphinx-doc/sphinx/issues/6702

i.e. The unicode issue is out of your hands.
