### ISSUE TITLE
index range error for csvtk csv2xlsx

### ISSUE THREAD

**Issue by ShannonDaddy** [shenwei356/csvtk#138]
Hi, I got the index range error when i'm using csvtk csv2xlsx, my version is v0.22.0.

![image](https://user-images.githubusercontent.com/6656888/114290486-aea77b80-9ab2-11eb-8ff6-849673923ee7.png)

[test.zip](https://github.com/shenwei356/csvtk/files/6302928/test.zip)

what's the maximum column number csvtk csv2xlsx supports? is it 26? because I succeed with a file with 26 columns, while failed with a file with 27 columns.

please check that for me, thanks, and the error message and test file is attached.

**Comment by shenwei356** [comment]
test.zip is "Not Found".

> what's the maximum column number csvtk csv2xlsx supports? is it 26? because I succeed with a file with 26 columns, while failed with a file with 27 columns.

I see, in Excel, column indexes are represented with 26 letters.  The 26th column is "Z", and the 27th column should be "AA".

I'll fix this later.

**Comment by shenwei356** [comment]
> what's the maximum column number csvtk csv2xlsx supports? is it 26? because I succeed with a file with 26 columns, while failed with a file with 27 columns.

[csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6293198/csvtk_darwin_amd64.tar.gz)
[csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6293199/csvtk_linux_amd64.tar.gz)
[csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/6293200/csvtk_windows_amd64.exe.tar.gz)

**Comment by ShannonDaddy** [comment]
> > what's the maximum column number csvtk csv2xlsx supports? is it 26? because I succeed with a file with 26 columns, while failed with a file with 27 columns.
> 
> fixed.
> 
> * [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6293198/csvtk_darwin_amd64.tar.gz)
> * [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/6293199/csvtk_linux_amd64.tar.gz)
> * [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/6293200/csvtk_windows_amd64.exe.tar.gz)

Thanks，it works, and i reupload the test.zip file.

**Comment by shenwei356** [comment]
Cheers! :fireworks:
