### ISSUE TITLE
[Suggestion] Mention homebrew installation method in README

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/csvtk#140]
I just [added csvtk](https://github.com/Homebrew/homebrew-core/pull/75531) to the Homebrew repository, so now it can be installed in a Mac using:

```
brew install csvtk
```

**Comment by shenwei356** [comment]
Thank you so much!

It's magic for just running `go build` to install, I guess it's the credit of "go module". It's complicated to build from golang source in the old time.
