### ISSUE TITLE
Remove empty columns?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/csvtk#142]
I would like to detect, and remove, empty columns from a CSV file.

By default "empty" would mean no data / zero length string.

Example:
```
# INPUT
A,B,C,D
a,b,,d
e,,,g
h,,i

% csvtk rmemptycol -

# OUTPUT
A,B,D
a,b,d
e,,g
h,,i
```

**Comment by shenwei356** [comment]
It's hard for column-wise filtering operation, but we can transpose the data.

`csvtk grep` supports searching on multiple columns, so we can use it to find rows not all empty in some columns.

```
cat t.csv \
    | csvtk transpose \
    | csvtk grep -f '-1' -r -p .+ \
    | csvtk transpose

A,B,D
a,b,d
e,,g
h,,i
```

**Comment by tseemann** [comment]
@shenwei356 that is nice solution
i did not think of using fuzzy column matching
this means `grep` is doing a "logical AND" (not "OR") for the yes/no decision.
thank you!

**Comment by shenwei356** [comment]
NO, it’s OR, matching any column
