### ISSUE TITLE
[Question]: testdata folder location with conda installs

### ISSUE THREAD

**Issue by tamuanand** [shenwei356/csvtk#144]
Hi

I am using ```csvtk v0.23.0``` downloaded via bioconda

Question: Where is ```testdata``` located with the conda install 
- I see ```testdata``` being used in the examples here - https://bioinf.shenwei.me/csvtk/usage/

I looked in the conda install directory and do not find it

Thanks

**Comment by shenwei356** [comment]
git clone https://github.com/shenwei356/csvtk

or download 

https://github.com/shenwei356/csvtk/archive/refs/tags/v0.23.0.zip

**Comment by tamuanand** [comment]
Thanks
