### ISSUE TITLE
Help with installing csvtk with Docker

### ISSUE THREAD

**Issue by tamuanand** [shenwei356/csvtk#145]
Hi

I am trying to have csvtk installed via Docker - I am running into issues and wanted to seek your help/opinion

[I have posted this as a question on StackOverflow](https://stackoverflow.com/questions/67854059/problems-installing-csvtk-with-docker-using-debianstretch-slim) regarding this.

On a slightly different note, I see you helped with docker install for ppc64le arch on this post - https://github.com/shenwei356/csvtk/issues/82

Thanks in advance

**Comment by tamuanand** [comment]
If it would help anyone, the question above was answered in SO - https://stackoverflow.com/a/67855461/10101904

**Comment by shenwei356** [comment]
Thanks for the feedback.

Here's a [Dockerfile](https://github.com/shenwei356/seqkit/blob/master/Dockerfile) from another similar tool, it may also be helpful.
