### ISSUE TITLE
filter2 and Date / Time fields

### ISSUE THREAD

**Issue by tseemann** [shenwei356/csvtk#146]
csvtk v0.23.0
```
# dates.csv
ID,Date
last year,2020-02-02
yesterday,2021-06-10
today,2021-06-11
tomorrow,2021-06-12
next year,2022-11-11


# all of these return all the rows - no filtering done?
csvtk filter2 -f '$Date<2021-06-11' dates.csv
csvtk filter2 -f '$Date<"2021-06-11"' dates.csv
csvtk filter2 -f "\$Date<'2021-06-11'" dates.csv

ID,Date
last year,2020-02-02
yesterday,2021-06-10
today,2021-06-11
tomorrow,2021-06-12
next year,2022-11-11


```
I trieed addeding ` 00:00:00` too, and read the `gocaluate` docs but notjing works.
I undestand the dates are converted to `float64` epoch values but how can i orce it to be parsed as a Date?
But maybe it shoudl also work as a regular string with lexiographic comparion?

**Comment by shenwei356** [comment]
https://github.com/Knetic/govaluate#escaping-characters

Does this help?

**Comment by tseemann** [comment]
Not that I can see.  
Have you ever filtered based on Date/Time before?
Is there any examples in your test suite?

**Comment by shenwei356** [comment]
Sorry, the last message was written on bus/subway, so it's not tested.

> Have you ever filtered based on Date/Time before?
No

I check the govaluate's document, and can't find a way to solve this in a short time. 

In its example, the two dates are recognized as DATE so the expression is invalid.

```
expression, err := govaluate.NewEvaluableExpression("'2014-01-02' > '2014-01-01 23:59:59'");
	result, err := expression.Evaluate(nil);
```

While for the expression with modifier/variable,  `$Date<"2021-06-11"`, the package tried to parse the `$Date` to `floats`:

    [ERRO] data: [last year 2020-02-02], err: Value '2020-02-02' cannot be used with the comparator '<', it is not a number

The `govaluate` package has not been updated for 4 years, we may find another one.

----

One way would be replacing the `Date` with the corresponding value before creating an expression, so it could be recognized as DATE. will try tomorrow.

**Comment by shenwei356** [comment]
I think I fix it.

```
$ csvtk pretty  dates.csv 
ID          1Date        value
---------   ----------   -----
last year   2020-02-02   3
yesterday   2021-06-10   4
today       2021-06-11   1
tomorrow    2021-06-12   4
next year   2022-11-11   6

$ csvtk filter2 -f '$1Date < "2021-06-11"' dates.csv  | csvtk pretty 
ID          1Date        value
---------   ----------   -----
last year   2020-02-02   3
yesterday   2021-06-10   4

$ csvtk filter2 -f '$2 < "2021-06-11"' dates.csv  | csvtk pretty 
ID          1Date        value
---------   ----------   -----
last year   2020-02-02   3
yesterday   2021-06-10   4

$ csvtk filter2 -f '$1Date < "2021-06-11" && $value > 3' dates.csv  | csvtk pretty 
ID          1Date        value
---------   ----------   -----
yesterday   2021-06-10   4

```

**Comment by shenwei356** [comment]
empty values are ignored.

```
$ csvtk pretty  dates.csv
ID          1Date        value
---------   ----------   -----
old time                 2
old time1   1949-10-01   
last year   2020-02-02   3
yesterday   2021-06-10   4
today       2021-06-11   1
tomorrow    2021-06-12   4
next year   2022-11-11   6

$ csvtk filter2 -f '$1Date < "2021-06-11"' dates.csv  | csvtk pretty 
[WARN] row 1: Value '' cannot be used with the comparator '<', it is not a number
ID          1Date        value
---------   ----------   -----
old time1   1949-10-01   
last year   2020-02-02   3
yesterday   2021-06-10   4
```

**Comment by shenwei356** [comment]
@tseemann does it work?

**Comment by tseemann** [comment]
Thanks @shenwei356 - this bug looks like it was quite a bit of work. Thank you for looking into it and fixing it
