### ISSUE TITLE
feature request: csvtk cut by content

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#148]
This is another feature request to consider. There may already be a way to do this, or a more elegant way to implement.

Consider a file (e.g. csv file) which we know contains a field or fields with a specific pattern in the entries, but we are not sure what that field or fields will be called (the user may choose something different every time).

We want to cut the field or fields that contain certain content, e.g.:

```
echo -ne "clones,id,values,meta\nCL-1,1,a;b,12\nCL-2,2,c,23\nCL-3,3,d;e;f,34\n" | csvtk cut -F -Content -p '^CL-.+'
clones
CL-1
CL-2
CL-3
```

Since there is a single field that matches the pattern '^CL-.+', it cuts that field and that one only, regardless of what is called.

```
echo -ne "clones,foo,id,values,meta\nCL-1,,1,a;b,12\nCL-2,CL-foo,2,c,23\nCL-3,CL-bar,3,d;e;f,34\n" | csvtk cut -F -Content -r -p '^CL-.+'
clones,foo
CL-1,
CL-2,CL-foo
CL-3,CL-bar
```
Here there are 2 fields that have at least one occurrence of '^CL-.+', and since we used the '-r' flag, we show both of them as the output of `csvtk cut -Content`. If we had run it without the '-r', then we would only show 'clones', as the field 'foo' doesn't match all the time.

For you to consider: as I said, there may already be a way of doing this elegantly without needing an extra feature implemented.

**Comment by shenwei356** [comment]
Let's rotate it.

```
$ echo -ne "clones,foo,id,values,meta\nCL-1,,1,a;b,12\nCL-2,CL-foo,2,c,23\nCL-3,CL-bar,3,d;e;f,34\n" \
    | csvtk transpose \
    | csvtk grep -H -f '-1' -r -p '^CL-' \
    | csvtk transpose
clones,foo
CL-1,
CL-2,CL-foo
CL-3,CL-bar
```

For the `-r`, we may add an option to requiring all fields to be matched with `query`, i.e., `all()` instead of `any()`.

**Comment by avilella** [comment]
That's great! I didn't know of the -f '-1' option. Very nice!

**Comment by shenwei356** [comment]
It means fields except for the 1st one.

```
  1. Single column
     csvtk cut -f 1
     csvtk cut -f colA
  2. Multiple columns (replicates allowed)
     csvtk cut -f 1,3,2,1
     csvtk cut -f colA,colB,colA
  3. Column ranges
     csvtk cut -f 1,3-5       # 1, 3, 4, 5
     csvtk cut -f 3,5-        # 3rd col, and 5th col to the end              # only supported by csvtk cut
     csvtk cut -f 1-          # for all                                      # only supported by csvtk cut
     csvtk cut -f 2-,1        # move 1th col to the end
  4. Unselect
     csvtk cut -f -1,-3       # discard 1st and 3rd column
     csvtk cut -f -1--3       # discard 1st to 3rd column
     csvtk cut -f -2-         # discard 2nd and all columns on the right.     # only supported by csvtk cut
     csvtu cut -f -colA,-colB # discard colA and colB


```
