### ISSUE TITLE
loss data

### ISSUE THREAD

**Issue by happydentist** [shenwei356/csvtk#150]
nice tool and speed.
But I got an error,
When my csv file which first character with # on every line(row), 
data would be loss after csvtk handle the data.
For example csv file like 
    #hcuhsd,122,ehfefj,
    &^jjddk,654,hdhjh,
after 
csvtk replace -H -f 4 -p "^$" -r "10003"
and result
    &^jjddk,654,hdhjh,10003
loss one row

**Comment by avilella** [comment]
I think you can avoid that by changing the '-C' flag from the default '#'
to something else.

**Comment by avilella** [comment]
$ echo -e "#foo\nbar" | csvtk pretty
bar
$ echo -e "#foo\nbar" | csvtk pretty -C '@'
#foo
bar

**Comment by happydentist** [comment]
Albert Vilella
Thank for your help.
I read the usage again.
The document was talk about it.
