### ISSUE TITLE
feature request: create new field from calculating length of string in field

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#153]
Hi,

This is either a feature request or a question as to how to achieve in an elegant way:

Is there a way of creating a new field which is the length of the string in another field? E.g. in pseudocode below:
```
$ seq 1 10 | csvtk add-header -n field1 | csvtk mutate -f field1 -n f1_len -p '^length(.+)$'
field1,f1_len
1,1
2,1
3,1
4,1
5,1
6,1
7,1
8,1
9,1
10,2
```

Thanks in advance

**Comment by shenwei356** [comment]
not supported.

**Comment by tseemann** [comment]
@avilella i've been wanting this feature too.
I don't think `datamash` has it either.
Very frustrating to have to switch to `awk` or `perl` here.

**Comment by shenwei356** [comment]
@avilella @tseemann 

```
$ (echo a; seq 0 42 200  ) \
    | csvtk mutate2 -t -n b -e "\$a + 50" -L 0 \
    | csvtk mutate2 -t -n len -e 'len($a, $b)'
a       b       len
0       50      3
42      92      4
84      134     5
126     176     6
168     218     6
```

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7037355/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7037359/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/7037362/csvtk_windows_amd64.exe.tar.gz)

**Comment by avilella** [comment]
Fantastic! Thank you very much!

**Comment by tolot27** [comment]
@shenwei356 Please can you implement the `len` function in `filter2` as well?

**Comment by shenwei356** [comment]
Sure, but it's midnight here, how about tomorrow.

And I decide to change expression evaluation package to https://github.com/antonmedv/expr someday , which has more functions. #172

**Comment by shenwei356** [comment]
> Please can you implement the len function in filter2 as well?

Done. And also fixed `len` and `ulen` in `mutate2`, where it could not be used for arithmetic operators.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7504711/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7504714/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/7504716/csvtk_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
Yes please open another issue with the demo file and commands.
