### ISSUE TITLE
feature request: CAN split fixed length file to CSV format?

### ISSUE THREAD

**Issue by happydentist** [shenwei356/csvtk#154]
Nice tool for csvtk
CAN split fixed length file to CSV format?

fixed length file like this
0000000858FIOKOYFIHH  123578007-2022806EURFI6357800720228068OKOYFIHH 
0000001537FIHANDFIHH 1234313130-1051135EURFI4331313001051135HANDFIHH
0000001537SEBANKGIRO12345885542-1459039BGCFK4580340334748099sgdswiud

to CSV like this，trim leading space or tailing space or other character
0000000858FI,OKOYFIHH,123,578007-2022806,EUR,FI6357800720228068,OKOYFIHH 
0000001537FI,HANDFIHH,1234,313130-1051135,EUR,FI4331313001051135,HANDFIHH
0000001537SE,BANKGIRO,12345,885542-1459039,BGC,FK4580340334748099,sgdswiud

1st column 12
2nd column 8
3rd column 5
4th column 14
5ht column 3
6th column 18
7th column 8

Many thanks!

**Comment by avilella** [comment]
Hi,

I am not 100% sure if this will work, but you can give it a try:
```
cat file | csvtk space2tab | csvtk tab2csv > file.csv
```

**Comment by happydentist** [comment]
Thanks for avilella.
But my original fixed length file not space delimited.
1st column for 12 character width, 2nd column for 8 character width, and so on.

**Comment by shenwei356** [comment]
sorry, not supported.
