### ISSUE TITLE
headers detox

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#155]
Hi, this is another feature request, unless there is already a way of doing this which I may not be aware of.

I am trying to make the headers of a file nicer to downstream steps, e.g. inputting into databases such as BigQuery, which require that the fields are alphanumeric + underscore, etc.

Would it be possible to have a new command that takes an input with headers, and "detoxifies" the header names so that anything non-database field name compliant is turned into an alphanumeric+underscores equivalent?

E.g.

```
echo -e "foo,bar,field with spaces,1 starts with number, has-dashes\n1,2,3,4,5" | csvtk header-detox
foo,bar,field_with_spaces,_1_starts_with_number,has_dashes
1,2,3,4,5
```

Thanks in advance,

**Comment by shenwei356** [comment]
```
$ echo -e "foo,bar,field with spaces,1 starts with number, has-dashes\n1,2,3,4,5" \
    | csvtk rename2 -F -f "*" -p "\W" -r _
foo,bar,field_with_spaces,1_starts_with_number,_has_dashes
1,2,3,4,5

$ echo -e "foo,bar,field with spaces,1 starts with number, has-dashes\n1,2,3,4,5" \
    | csvtk rename2 -F -f "*" -p "\W" -r _ \
    | csvtk rename2 -F -f "*" -p "^(\d)" -r "_\$1"
foo,bar,field_with_spaces,_1_starts_with_number,_has_dashes
1,2,3,4,5
```
