### ISSUE TITLE
`minus` or `join -X` or `comm`

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#157]
Use case: find identifiers in one file that are missing from another.

I'm thinking unix `comm` (it produces three-column output: that's not relevant to csvtk!):
```
Compare sorted files FILE1 and FILE2 line by line.
With no options, produce three-column output.  
Column one contains lines unique to FILE1, column two contains lines unique to FILE2, and column three contains lines common to both files.
  -1              suppress 1 (lines unique to FILE1)
  -2              suppress 2 (lines unique to FILE2)
  -3              suppress 3 (lines that appear in both files)
```

`csvtk join` has these options:
```
  OPTION         RESULT
  none (inner)   keep 3,   suppress 1,2
  -k, -L (left)  keep 1,3, suppress 2
  -O (outer)     keep 1,2,3
```
What I need is something like
```
  OPTION          RESULT
  -X (exclusive)  keep 1, suppress 2,3
```

But maybe the best is to add 1 or 2 new sub-commands?
```
  COMMAND   SAME AS    DESCRIPTION   
  minus     comm -23   return rows of the first file that don't appear in the second
  comm      join -O    return rows appearing in either file
  comm -2   join -L    return all rows from the first file
  comm -12  join       return rows common to both files
```

**Comment by shenwei356** [comment]
minus: `csvtk grep -v` (simiar to `grep -v`)

```
  -v, --invert                invert match
```

**Comment by VladimirAlexiev** [comment]
`csvtk grep -v` doesn't take 2 files as arguments.

**Comment by shenwei356** [comment]
How about piping to two `csvtk grep -v`?

    csvtk grep -v -P file2  file1 | csvtk grep -v -P file3

**Comment by VladimirAlexiev** [comment]
I think we'd need to use this: first extract the relevant field from `file` then pass the values to grep on stdin (`-P -`):

`csvtk cut -f field file2 | csvtk grep -v -P - -f field file1`

If this sounds reasonable, please close.
