### ISSUE TITLE
comb -d option missing in -h 

### ISSUE THREAD

**Issue by tseemann** [shenwei356/csvtk#158]
I think the `csvtk comb -h` is incorrect?
It seems to be missing the important `-d` option?
`-d` is in the web docs.

```Flags:
  -h, --help          help for comb
  -i, --ignore-case   ignore-case
  -S, --nat-sort      sort items in natu>  -n, --number int    number of items in>
  -s, --sort          sort items in a co>
```

**Comment by shenwei356** [comment]
Global Flags:
  -c, --chunk-size int         chunk size of CSV reader (default 50)
  -C, --comment-char string    lines starting with commment-character will be ignored. if your header row starts with '#', please assign "-C" another rare symbol, e.g. '$' (default "#")
  -d, --delimiter string       delimiting character of the input CSV file (default ",")
  -E, --ignore-empty-row       ignore empty rows

**Comment by tseemann** [comment]
Could you please add an example to help to make that clear please?
To prevent me asking again in 2 years? :)
Thank you

**Comment by shenwei356** [comment]
sure
