### ISSUE TITLE
request for more options of keep in "csvtk join"

### ISSUE THREAD

**Issue by dawnmy** [shenwei356/csvtk#16]
`csvtk join`:

### keep rows according to specified files (one or more based on row union)
For instance:
```shell
-k 1,2 # to keep all rows of the union of first and second file
-k 1 # to keep all rows of first file
-k 2-7 # to keep all rows of the union of file 2 to 7 
-k 1- # to keep all rows of the union of all files
```

**Comment by shenwei356** [comment]
> -k "name1;name2" # to keep all rows of fields "name1", "name2"

Not clear.

> -k 1 # to keep all rows of first

First what?

> -k 2-7 # to keep all rows of fields 2 to 7 

Why not just "cut"  these fields after joining.

> -k 1- # to keep all rows from all fields

Field range `1-` not supported.

**Comment by dawnmy** [comment]
Sorry for the mistake. I revised the description of the request.
