### ISSUE TITLE
xlsx2csv raw output

### ISSUE THREAD

**Issue by aborruso** [shenwei356/csvtk#165]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem

I have [this](https://github.com/shenwei356/csvtk/files/7114031/Covid.Report.03.Settembre.xlsx) input file, in which I have a cell whose value is `03/09/2021`, that is formatted as `3-set-2021`.

![image](https://user-images.githubusercontent.com/30607/132176212-9d9a5c9d-3193-4f5f-bdad-5373b99b879f.png)

If I run `csvtk xlsx2csv Covid\ Report\ 03\ Settembre.xlsx | head` I do not have the raw value (`03/09/2021`), but the formatted one (`3-Sep-2021`).

I think it's important to have the way to export raw data: how to do it in csvtk?

Thank you

**Comment by shenwei356** [comment]
I added a new command `fmtdate` [recently](https://github.com/shenwei356/csvtk/issues/159#issuecomment-905166986).

    csvtk xlsx2csv t.xlsx \
        | csvtk fmtdate -f 9 --format "DD/MM/YYYY" --keep-unparsed

**Comment by aborruso** [comment]
As usual, thank you for all.

It would be great to have an option to export the raw values, without specifying format or field number.
In example in csvkit, there a no inferencing option.

Could I add it as feature request?

**Comment by shenwei356** [comment]
It's already [discussed](https://github.com/shenwei356/csvtk/issues/159#issuecomment-904434733), and I recheck the document and codes of `excelize` package again but did not find any options :(

**Comment by aborruso** [comment]
once again, thank you
