### ISSUE TITLE
option to skip leading/trailing lines

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#166]
I'm working on https://sam.gov/api/prod/fileextractservices/v1/api/download/Entity%20Registration/Public%20V2/SAM_PUBLIC_UTF-8_MONTHLY_V2_20210905.ZIP?privacy=Public

It is 124 Mb, 804k records, vbar-separated, 142 fields, and each record ends in `!end`.

There are header and footer lines that should be discarded:
```
BOF PUBLIC V2 00000000 20210905 0804185 0006956
...
EOF PUBLIC V2 00000000 20210905 0804185 0006956
```

Processing a few sample lines works ok, eg here's to transpose some sample rows:
```
grep -E "NLXHHB71VMK5|ZMTEH4J6JCM7|HD78E29EMEC1|MJ5MN6SGYKF6" SAM_PUBLIC_UTF-8_MONTHLY_V2_20210905.dat |csvtk -d "|" -T transpose
```

However, trying to get stats of some field is not so easy because the first line throws off the field count:
```
csvtk -H -I -d "|" freq -f 6 SAM_PUBLIC_UTF-8_MONTHLY_V2_20210905.dat
[ERRO] field (6) out of range (1) in file: SAM_PUBLIC_UTF-8_MONTHLY_V2_20210905.dat
```

To work around this I used `tail` to skip the first line:
```
tail -n +2 SAM_PUBLIC_UTF-8_MONTHLY_V2_20210905.dat | csvtk -H -I -d "|" freq -f 6
```

Maybe it's a good idea to introduce corresponding options, eg:
```
-s N    skip N leading rows
-S N    skip N trailing rows
```

**Comment by shenwei356** [comment]
For atypical formats, we may ask users to preprocess them. :(

**Comment by VladimirAlexiev** [comment]
Yes, that is a reasonable workaround.
