### ISSUE TITLE
What is the best way to print line number as the first column

### ISSUE THREAD

**Issue by san-r** [shenwei356/csvtk#170]
This is not an issue but question. As of now, csvtk sub-commands supporting the flag **-n** or **--line-number** to "**print line number as the first column ("n")**" are as under:

**grep
filter
filter2
sample**

One way to print line number as the first column at the end of workflow is as under:

_csvtk sub-command ... |^
csvtk another-sub-command ... |^_
**csvtk grep -n -f1 -r -p ".*" |^**
csvtk pretty

I'm wondering if there a better (more processor and RAM friendly) way to to print line numbers than using
**csvtk grep -n -f1 -r -p ".*"**

**Comment by shenwei356** [comment]
I don't think making all commands support this is a good idea. 

Maybe adding a new command `cat` with a `-n` option to print the line numbers.

**Comment by shenwei356** [comment]
In the next version, you can easily use 

```
$ csvtk cut -f 1- -Z testdata/names.csv 
row,id,first_name,last_name,username
1,11,Rob,Pike,rob
2,2,Ken,Thompson,ken
3,4,Robert,Griesemer,gri
4,1,Robert,Thompson,abc
5,NA,Robert,Abel,123

$ csvtk filter2 -f '$id>2' -n  testdata/names.csv 
row,id,first_name,last_name,username
1,11,Rob,Pike,rob
3,4,Robert,Griesemer,gri
```


Related changes:

- add a new global flag `-Z/--show-row-number`, supported commands: cut, csv2tab, csv2xlsx, tab2csv, pretty.
- the colum name of row number changes from "n" to "row":  csv2xlsx, csv2tab, cut, filter, filter2, grep, pretty, sample, tab2csv.
