### ISSUE TITLE
filter2 Cannot transition token types from STRING to VARIABLE caused by single quotes

### ISSUE THREAD

**Issue by tolot27** [shenwei356/csvtk#174]
I'm using csvtk v0.23 and get an error message if I try to filter against a string containing single quotes.

Example:
```
echo -e "Organism\nHuman 'child'" | csvtk -t filter2 -f '$Organism=="test"'
[ERRO] Cannot transition token types from STRING [Human ] to VARIABLE [child]
```

The lazy quotes parameter does not help in this case. Single quoting should not matter for tab-separated input and also not for csv because it uses double quotes.

**Comment by shenwei356** [comment]
Fixed. I'm tired of adding patches for these two commands since https://github.com/Knetic/govaluate is not active anymore, I will soon replace it with https://github.com/antonmedv/expr. #172 



```
$ echo -e "Organism\nHuman 'child'\nHuman \"child\"\nHuman 'child\nHuman \"child\ntest\n\"test\"\n'test'\n"
Human 'child'
Human "child"
Human 'child
Human "child
test
"test"
'test'

$ echo -e "Organism\nHuman 'child'\nHuman \"child\"\nHuman 'child\nHuman \"child\ntest\n\"test\"\n'test'\n" \
    | csvtk -t filter2 -f '$Organism == "test"' -l
Organism
test
test

```


- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7559131/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7559132/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/7559133/csvtk_windows_amd64.exe.tar.gz)

**Comment by tolot27** [comment]
Many thanks!

**Comment by tolot27** [comment]
Unfortunately, the new build have not the same flags for "mutate2" anymore. For instance, there is no flag `-n` to specify a name for the column to create.

Flags of previous build:
```
  -L, --digits int          number of digits after the decimal dot (default 2)
  -e, --expression string   arithmetic/string expressions. e.g. "'string'", '"abc"', ' $a + "-" + $b ', '$1 + $2', '$a / $b', ' $1 > 100 ? "big" : "small" '
  -h, --help                help for mutate2
  -n, --name string         new column name
  -s, --numeric-as-string   treat even numeric fields as strings to avoid converting big numbers into scientific notation
```

Flags of new build:
```
  -w, --decimal-width int   limit floats to N decimal points (default 2)
  -L, --digits int          number of digits after the decimal dot (default 2)
  -e, --expression string   arithmetic/string expressions. e.g. "'string'", '"abc"', ' $a + "-" + $b ', '$1 + $2', '$a / $b', ' $1 > 100 ? "big" : "small" '
  -h, --help                help for mutate2
  -s, --numeric-as-string   treat even numeric fields as strings to avoid converting big numbers into scientific notation
```
`-w` is similar to `-L`.

**Comment by shenwei356** [comment]
Sorry, it's [a mistake](https://github.com/shenwei356/csvtk/commit/7e54d7ae8e3365e086c3839714528d3f64dac751#diff-846d7b29899c3c9884fb20a808323ae5c6dc801c3ad2226fb94f228ab97e5bd5L481).

[csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7568434/csvtk_darwin_amd64.tar.gz)
[csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7568436/csvtk_linux_amd64.tar.gz)
[csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/7568438/csvtk_windows_amd64.exe.tar.gz)

**Comment by tolot27** [comment]
Many thanks for the hot fix!
