### ISSUE TITLE
Question: Use csvtk to split large file into multiple small files based on column(s)

### ISSUE THREAD

**Issue by tamuanand** [shenwei356/csvtk#175]
Hi

Is it possible to use `csvtk` to split a given file into multiple files

```
#contents of large_file.csv
1,2,3,4,5,6,7,8
a,b,c,d,e,f,g,h
q,w,e,r,t,y,u,i
a,s,d,f,g,h,j,k
z,x,c,v,b,n,m,z
```

I now want multiple files like this:
```
# contents of 1.csv
1,2
a,b
q,w
a,s
z,x

# contents of 2.csv
1,3
a,c
q,e
a,d
z,c

# contents of 3.csv
1,4
a,d
q,r
a,f
z,v

and so on...
```
I can do this currently with `awk` like this:

```awk -F, 'BEGIN{OFS=",";} {for (i=1; i < NF; i++) print $1, $(i+1) > i ".csv"}'   large_file.csv```

It would be nice if `csvtk` could have some feature like this - something like the [split in seqkit](https://bioinf.shenwei.me/seqkit/usage/#split)

**Comment by shenwei356** [comment]
It's easy by using `for` + `csvtk cut`. There's no need to create another command.

    for i in $(seq 2 $(csvtk ncol data.csv)); do 
        csvtk cut -f 1,$i data.csv > $i.csv;
    done

If you want it to be faster, replace `for` with `parallel` or other tools.

    seq 2 $(csvtk ncol data.csv) \
        | parallel 'csvtk cut -f 1,{} data.csv > {}.csv'

**Comment by tamuanand** [comment]
Thanks
