### ISSUE TITLE
`summary -g`: without -f; joint vs separate grouping; numeric sort

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#177]
My first task when exploring a CSV is to see value distributions for key fields.

---

A. I used to do it like this (the last command sorts by prevalence):
```
csvtk cut -f key | sort | uniq -c | sort -rn
```
Now I can do it like this:
```
csvtk summary -g key -f dummy 
```
where `dummy` is an existing fully-filled field.

But what I really want to see is the count of **rows** grouped by `-g key` not the count of some `dummy` field.
Can you allow `-f` to be optional when `-g` is specified?

---

B. When there are many key fields, I want to see their value distributions separately. Now I have to use 2 commands:
```
csvtk summary -g key1
csvtk summary -g key2
```
This won't work because it counts the **joint** distribution of the two fields:
```
csvtk summary -g key1,key2
```
Is it possible to have a variant like this to count the **separate** distributions of the two fields?
```
csvtk summary -g key1 -g key2
```

--- 

C. Key values are sorted alphabetically; it would be nice to have an option to sort by prevalence (like `uniq -c | sort -rn` does).
Currently there's no way to do it because `csvtk summary` outputs fields with embedded colon (eg `dummy:count`) but `csvtk sort` doesn't accept them:
```
csvtk summary -g key -f dummy | csvtk sort -k dummy:count:rn
[ERRO] invalid sort type: count
```
It would be nice to allow eg this syntax:
```
csvtk summary -g key1:nr -g key2:r  # 2 separate distributions, one decreasing numeric, another reverse alphabetical
csvtk summary -g key1,key2:nr    # joint distribution, decreasing numeric
```

**Comment by shenwei356** [comment]
try `csvtk freq`

**Comment by VladimirAlexiev** [comment]
Thanks! The only missing item is B but now that I think of it, its not very sensible
