### ISSUE TITLE
[ERRO] CreateFile Name': The system cannot find the file specified

### ISSUE THREAD

**Issue by Remiol** [shenwei356/csvtk#178]
Hello
I do have the latest Windows version of csvtk (64 bits): csvtk v0.24.0

Some features are working (ncol, nrow, summary) but most features don't work in my case.

```
csvtk freq -f 'First Name  myfile.csv
[ERRO] CreateFile Name': The system cannot find the file specified
```

The same for almost all other features of csvtk.

What did I do wrong?

**Comment by shenwei356** [comment]
You can't use a bare quote `'` in the command line. Use:

    csvtk freq -f "First Name"  myfile.csv

If the quote IS a part of the column name, use the double quote:

    csvtk freq -f "'First Name"  myfile.csv
