### ISSUE TITLE
[Feature request] New functions "argmin" and "argmax" for `summary`

### ISSUE THREAD

**Issue by tetedange13** [shenwei356/csvtk#181]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your *requested feature*
Thanks for developping `csvtk`, it really empowered my manipulation of CSV/TSV files !!

I thought to possibly useful new functions for `summary` subcommand: **argmax** and its counterpart **argmin**
=> I am not sure if this is relevant name for this type of functions, I call them like that because of [their Python (numpy) equivalent](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

To put it in words: return the index (1-based or 0-based depending on your internal representation) of the min/max value for a given column 

Or maybe this is something that can already be achieved with a few commands ?
<br>

Thanks again !
Kind regards.
Felix.

**Comment by shenwei356** [comment]
added.

    $ echo -ne "3\n1\n5\n4\n" | ./csvtk summary -H -f 1:argmin -f 1:argmax
    2.00,3.00
