### ISSUE TITLE
Feature Request: Regex based joins similar to the R package fuzzy_join

### ISSUE THREAD

**Issue by harish0201** [shenwei356/csvtk#184]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ x] describe the problem
Hi Shen! Hope you're well! I'm in love with this package and had a feature request. Would it be possible to implement regex based joins like in the R package fuzzyjoin? See the webpage for Fuzzyjoin: https://www.rdocumentation.org/packages/fuzzyjoin/versions/0.1.6
* [x] provide a reproducible example
Say I have a couple of TSV files: one with bioMart Annotation and the other are a bunch of genes:
gene matrix:
````
geneA 10 15 40
geneB 56 5 29
````

biomart annotation:
````
gene_id biotype gene_stable_id
geneA.ver1 lncRNA ENSGXXXXXX
geneB.ver5 protein_coding ENSGYYY
````
expectation: `csvtk join -t -o joined_annot.txt -l -k gene.matrix biomart.txt`
outcome:
````
geneA 10 15 40 geneA.ver1 lncRNA ENSGXXXXXX
geneB 56 5 29 geneB.ver5 protein_coding ENSGYYY
````

I hope the example makes sense! I routinely use the package fuzzyjoin where csvtk doesn't aptly cover it (I might be missing the function if already available), so I thought to check with you!

Thank you!
Harish

**Comment by shenwei356** [comment]
Use `csvtk mutate` to extract the gene_id without the version from column `gene_id` as a new column that could be used for joining as usual. 

```
$ csvtk join -t -f '1;4'  \
    gene.matrix \
    <(csvtk mutate -t -f gene_id -n gene_id2 -p '^(.+?)\.' biomart.txt | csvtk del-header)
geneA   10      15      40      geneA.ver1      lncRNA  ENSGXXXXXX
geneB   56      5       29      geneB.ver5      protein_coding  ENSGYYY
```
