### ISSUE TITLE
[BUG]Wrong filter2 behaiver when header line contain ”.“

### ISSUE THREAD

**Issue by Whale-fall** [shenwei356/csvtk#186]
CSVTK version v0.23.0
raw file like this:
`
head vdjdb.slim.txt | cut -f 1,2,3,4,5
`
![image](https://user-images.githubusercontent.com/22662209/169199843-4b7962c5-4aa9-45e9-a766-5b45128738fd.png)

when I try to select rows by "antigen.gene" using filter2 an error appears
`
head vdjdb.slim.txt | cut -f 1,2,3,4,5  \\
    | csvtk filter2 -t -f '$species == "HomoSapiens" && $antigen.gene=="Tat"' 
`
`Unable to parse numeric value '.' to float64`

**Comment by shenwei356** [comment]
Try this:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/8730135/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/8730137/csvtk_linux_amd64.tar.gz)

```

Variables formats:
  $1 or ${1}                        The first field/column
  $a or ${a}                        Column "a"
  ${a,b} or ${a b} or ${a (b)}      Column name with special charactors, 
                                    e.g., commas, spaces, and parentheses

```

simple tests:

```
$  echo -ne "a\n1\n2\n" | ./csvtk  filter2 -t -f  '$a > 1'
a
2

$  echo -ne "a\n1\n2\n" | ./csvtk  filter2 -t -f  '${a} > 1'
a
2

$  echo -ne "a\n1\n2\n" | ./csvtk  filter2 -t -f  '$1 > 1'
a
2

$  echo -ne "a (b)\n1\n2\n" | csvtk  filter2 -t -f  '${1} > 1'
a (b)
2

$ echo -ne "a (b)\n1\n2\n" | csvtk  filter2 -t -f  '${a (b)} ==  1'
a (b)
1

$  echo -ne "a,b\n1\n2\n" | ./csvtk  filter2 -t -f  '${a,b} > 1'
a,b
2

```
