### ISSUE TITLE
Feature request: missing data handling in plotting functions

### ISSUE THREAD

**Issue by taprs** [shenwei356/csvtk#188]
Hi Wei, thank you for your great work!

It would be cool to make plotting functions work when there are rows with missing data. With `csvtk v0.24.0` an error pops up when trying to plot a histogram with missing data:

```
$ echo $'1,1\n1,2\n,2'
1,1
1,2
,2
$ echo $'1,1\n1,2\n,2' | csvtk plot hist -f 1
[ERRO] fail to parse data:  at column: 1. please choose the right column by flag -f (--data-field)
```

**Comment by shenwei356** [comment]
Added a new flag `--skip-na` to `csvtk plot`:

      --na-values strings    NA values, case ignored (default [,NA,N/A])
      --skip-na              skip NA values in --na-values

Rember to use `-H` for data with no header line:

    echo $'1,1\n1,2\n,2' | csvtk plot hist -H -f 1 --skip-na | display

Binaries:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/8898179/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/8898186/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/8898195/csvtk_windows_amd64.exe.tar.gz)

**Comment by taprs** [comment]
Hmm, but why not making it a default behavior, at least for empty fields?
