### ISSUE TITLE
csvtk -split not parsing properly

### ISSUE THREAD

**Issue by lborcard** [shenwei356/csvtk#190]
Hello,

### Describe your issue

* [ ] describe the problem
I need to parse a file for barcode information in a CSV format and it creates files like that :

`all_infos-@<5::;87..8>67@@:94445;8888)(06787.txt`
`all_infos-barcode05.txt`
Additionnally some files which should be containing **e.g** barcode04 only also contain barcode01.

file.csv  tab separated created by pasting two files together:
```
a7e20a53-de62-4db4-b93e-a5d47bda22da   barcode01
33983567-6bfd-4aa5-b41a-5d5f59abce57   barcode01
6f614c99-569e-4ab0-8b72-cc1f0971d673   barcode04
0927a77f-4c01-4122-834c-31c8f7d5390e   barcode02
10439b5d-23b8-4bc9-92c9-cc5a9f5cf2ca   barcode06
3f41bab7-0452-443b-ba85-72b991819bd2   barcode05
61af8107-3fe9-4f17-8380-5947727a0906   barcode01
af9a61a1-a019-48e6-b95c-faaad8ce60ac   barcode03
48302bcf-11db-47e4-a900-747dd4c979a1   barcode01
````

my command:

`cat file.csv | csvtk -t -l split -f 2 -o Groups/` 

thank you for your help

**Comment by shenwei356** [comment]
add `-H` if no header line is given
