### ISSUE TITLE
[Suggestion] Add a tail command

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/csvtk#194]
As far as I know, there's no way to easily inspect the last `N` records of a `.csv` file in a way that includes the header. I assume this could be achieved by reading the first line (the header) and skip to the last `N` lines of the file.

**Comment by tetedange13** [comment]
Hi @apcamargo ,
<br>

I managed to do this with `awk` and `tac` (inspired from "**awk** Solution" of this answer : https://unix.stackexchange.com/a/139099)

### Input CSV
```
==> test.csv <==
id,age,gender
1,39,M
2,25,M
3,36,F
4,45,F
```

### One-liner
`tac test.csv | awk -v nbr=2 'NR<=nbr { prev=$0; print } END { if($0!=prev){print} }' | tac`

### Output (pretty)
```
id   age   gender
--   ---   ------
3    36    F
4    45    F
```

### Explanations
* "`N` last rows" in your question <--> `nbr` awk variable defined
* Mandatory to store previous line (-> `prev=$0` in above cmd) and test for equality before printing last line
=> To avoid double printting header if `nbr > nb_records`
<br>

Hope this helps !
Have a nice day,
Felix.

**Comment by shenwei356** [comment]
Thank you @tetedange13
