### ISSUE TITLE
[Suggest a new feature] Hash command

### ISSUE THREAD

**Issue by mando7** [shenwei356/csvtk#196]
Is it possible in the future to add a command that creates a new column with a hash of another column? 
A new anonymized column that would contain a uuid or md5 or sha or other hashing algorithm.
For example: `csvtk hash md5 -f 2 -n "id" -f 5 -n "anonymous"`
`csvtk hash uuid -f 2 -n "id" -f 5 -n "anonymous"`
`csvtk hash sha -f 2 -n "id" -f 5 -n "anonymous"`.

I hope I was understandable.
Thanks again for your tool.

**Comment by shenwei356** [comment]
Sound like a rare scenario

**Comment by avilella** [comment]
I find myself wanting to do this as well:

`csvtk mutate2 -n md5_field1 -e 'md5($field1)'`

Similar to an operation that I already find very useful:

`csvtk mutate2 -n len_field1 -e 'len($field1)'`

Thanks
