### ISSUE TITLE
csv2xlsx output number as number instead of text

### ISSUE THREAD

**Issue by litd** [shenwei356/csvtk#198]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
#192

**Comment by litd** [comment]
Thanks for quick response.
