### ISSUE TITLE
functionality request for the partial match of the grep command

### ISSUE THREAD

**Issue by dawnmy** [shenwei356/csvtk#2]
Hope the grep command can suport the partial match of given field and highlight the matched part just like the grep on Linux.

**Comment by shenwei356** [comment]
use flag -r (--use-regexp) for partial match. highlight could be taken into consideration

**Comment by shenwei356** [comment]
Matched parts are highlighted as red now in `grep`

![](http://shenwei356.github.io/csvtk/files/grep_result.png)

**Comment by dawnmy** [comment]
Cool!

**Comment by shenwei356** [comment]
I've fixed the bug of highlight failing in Windows. Please try it
