### ISSUE TITLE
Q: Does csvtk have an equivalent operation to csvkit's csvclean ?

### ISSUE THREAD

**Issue by kmatt** [shenwei356/csvtk#20]
I need a fast filter to parse csv file lines and drop those that are unparsable, as with https://csvkit.readthedocs.io/en/1.0.2/scripts/csvclean.html

csvclean works in a shell pipe (PR 781) but is limited in speed.

**Comment by shenwei356** [comment]
Not supported now. 
`csvtk` can only handle valid CSV/TSV format now.
For a bad format, it raises an error like:

    [ERRO] line 2, column 0: wrong number of fields in line
