### ISSUE TITLE
xlsx2csv treat small number (padj < 1e-25) as 0

### ISSUE THREAD

**Issue by litd** [shenwei356/csvtk#201]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
It seems to be a bug of the [excelize](https://github.com/qax-os/excelize/) package, which is fixed simply by updating the version.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/9642956/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/9642957/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/9642958/csvtk_windows_amd64.exe.tar.gz)

**Comment by litd** [comment]
Thanks!
