### ISSUE TITLE
[Feature request] join option to add filename as prefix

### ISSUE THREAD

**Issue by tetedange13** [shenwei356/csvtk#202]
### Prerequisites

- [x] `csvtk version` --> **v0.24.0**
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)
<br>

### Describe your issue

I often use `csvtk join` to produce a matrix, using it on several files with : 
* 1 (or several) column(s) to join on
* 1 single other column with values of interest (mean coverage for eg.)

I would love to have an option to **add each filename as a prefix for all columns that were not used for joining**
(for now I achieve this by creating for each file a corresponding `.tmp` with column of interest properly named with each filename, then I `csvtk join *.tmp`)
<br>

#### Input files
```
==> phones1.csv <==
username,number
gri,11111
rob,12345
ken,22222
shenwei,99999

==> phones2.csv <==
username,number
gri,22222
rob,56789
ken,33333
shenwei,77777

==> phones3.csv <==
username,number
gri,33333
rob,98765
ken,44444
shenwei,88888
```
#### Expected result
`csvtk join --new-option phones{1,2,3}.csv | csvtk pretty`
```
username   phones1.csv-number   phones2.csv-number   phones3.csv-number
--------   ------------------   ------------------   ------------------
gri        11111                22222                33333
rob        12345                56789                98765
ken        22222                33333                44444
shenwei    99999                77777                88888
```
Each file extension can be kept or removed, as you want
=> But I guess it is **simpler to keep it** and let user decide to add ` | sed '1s/\.csv//g'`, if he does not want it
<br>

### csvtk is a wonderful tool, thanks for developping it !
Have a nice day,
Felix.

**Comment by avilella** [comment]
This is a very useful new feature, thanks for your efforts.

Could we add an '--interleaved' flag that when added, interleaves the
fields in the output? E.g. see below:

file1 field names:
a
b
c
d

file2 field names:
a
b
c
d

file3 field names:
a
b
c
e

Using the `--interleaved` flag, the output would be the following fields in
the order below:

./csvtk join  file{1,2,3}.csv -A -f 1 --interleaved | csvtk headers

Output:

a

file1.csv-b

file2.csv-b

file3.csv-b

file1.csv-c

file2.csv-c

file3.csv-c

file1.csv-d

file2.csv-d

file3.csv-e

Thanks for your consideration,

**Comment by shenwei356** [comment]
That would be a mess if these files have different numbers of columns.
