### ISSUE TITLE
csvtk pretty option to wrap text within a column

### ISSUE THREAD

**Issue by vkkodali** [shenwei356/csvtk#206]
I think this option does not currently exist so this is likely a feature request.
The `-W` option with `csvtk pretty` is quite useful when dealing with tables that have some really wide fields. However, I imagine it's not unusual for everyone to come across tables with (somewhat) wide fields for which we would like to see the data. Having an option to wrap text such that it creates multiple lines will be helpful. 

An example to illustrate this:
```bash
## test file
$ cat test.csv 
first_name,last_name,comment
John,Doe,short comment
Jane,Doe,somewhat long comment that I would like to see 
Jack,Doe,another not-so-long comment

## pretty print without column max width
$ csvtk pretty test.csv 
first_name   last_name   comment
----------   ---------   -----------------------------------------------
John         Doe         short comment
Jane         Doe         somewhat long comment that I would like to see 
Jack         Doe         another not-so-long comment

## pretty print with max col width
$ csvtk pretty -W 25 test.csv 
first_name   last_name   comment
----------   ---------   -------------------------
John         Doe         short comment
Jane         Doe         somewhat long comment tha
Jack         Doe         another not-so-long comme

## new option --wrap to wrap text in a column
$ csvtk pretty -W 25 --wrap test.csv
first_name   last_name   comment
----------   ---------   -------------------------
John         Doe         short comment
Jane         Doe         somewhat long comment 
                         that I would like to see
Jack         Doe         another not-so-long 
                         comment
```

**Comment by avilella** [comment]
I really like the idea of the `-W 25` --wrap or --clip option.

I would use it often if it was available.

Bests,

**Comment by shenwei356** [comment]
Yes, the idea is great. But the package https://github.com/tatsushid/go-prettytable does not support cells containing new line characters, https://github.com/bndr/gotabulate seems to do. If there's no existing way, I can also implement one, but not today.
