### ISSUE TITLE
wildcards on windows

### ISSUE THREAD

**Issue by ggrothendieck** [shenwei356/csvtk#210]
Would be nice if wildcards worked on Windows.

```
csvtk concat *.csv
```

or at least if --infile-list supported stdin

```
dir/b *.csv | csvtk concat --infile-list -
```

**Comment by shenwei356** [comment]
Hmm, use two steps:

```
dir/b *.csv > %tmp%/list.txt

csvtk concat --infile-list %tmp%/list.txt

```

**Comment by ggrothendieck** [comment]
I know one can create a text file of names and then use it.  That is what I do now.  But it seems a lot of work compared to using a wildcard or stdin.

**Comment by shenwei356** [comment]
I see. The option `--infile-list` supports STDIN now.

- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/10032339/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/10032342/csvtk_windows_amd64.exe.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/10032329/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/10032335/csvtk_darwin_arm64.tar.gz)

**Comment by ggrothendieck** [comment]
Thanks!
