### ISSUE TITLE
minor tweak to the documentation of csvtk cut

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#211]
Currently the documentation says that one can do:

```
csvtk cut -f -1--3

4. Unselect
   csvtk cut -f -1,-3       # discard 1st and 3rd column
   csvtk cut -f -1--3       # discard 1st to 3rd column
   csvtk cut -f -2-         # discard 2nd and all columns on the right.
   csvtu cut -f -colA,-colB # discard colA and colB
```

but the binary will complain unless one switches the order to:

```
csvtk cut -f -3--1
```

I've been caught by it a few times, it should be a small documentation change, if I am right in identifying the issue.

**Comment by shenwei356** [comment]
Deleted the example. It might be supported in very early versions, I'm not sure.
