### ISSUE TITLE
A good utility to calculate date/time differences

### ISSUE THREAD

**Issue by Gavin-Holt** [shenwei356/csvtk#213]
Hi,

I was very excited to discover CSVtk and delighted that I could create data pipelines.

However, my use-case requires me to calculate date/time intervals to see how long patients wait for surgery (hours for emergencies, days for elective surgery). I would like to append new fields with the calculations.

Does anyone know of a good utility that allows me to calculate date/time differences (on a Windows machine) in a pipeline?

Good equates to:

- Free, with compiled executables for Windows.
- Read and write to stdin/stdout.
- Works at the command line and in a batch file, without having to ["escape" multiple characters](https://ss64.com/nt/syntax-esc.html), as this is the nightmare of trying to use awk at the command line in windows.

I guess I might need several functions:

- now(output-format)
- date2str(data,output-format)
- str2date(data,input-format)
- datedif(date1,date2,output-format)

For my current project, I have had to manually edit the source data using Excel, breaking automation - I feel dirty!

Kind Regards Gavin Holt

**Comment by derekmahar** [comment]
If you could run your data pipeline in [Windows Subsystem for Linux](https://learn.microsoft.com/en-ca/windows/wsl/) or [Cygwin](https://cygwin.com/), [dateutils](http://www.fresse.org/dateutils/) should meet your requirements.

**Comment by Gavin-Holt** [comment]
I have found other ways, thank you all.
