### ISSUE TITLE
 Add a option to csv2xlsx  for output number as Text or number

### ISSUE THREAD

**Issue by zuisong** [shenwei356/csvtk#217]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

### Thank you

```shell
$ echo 8911111111111111111111111173 | csvtk  -H csv2xlsx -o /tmp/tempfile  &&  csvtk xlsx2csv   /tmp/tempfile
8911111111111111000000000000
```

output has lost some text. 

Maybe we can add a option to csv2xlsx control output number as Text or number. 
It seems like 
```shell
$ echo 8911111111111111111111111173 | csvtk  -H csv2xlsx --number-as-text -o /tmp/tempfile  &&  csvtk xlsx2csv   /tmp/tempfile
8911111111111111111111111173
```

**Comment by zuisong** [comment]
Link issue:  https://github.com/shenwei356/csvtk/issues/192

**Comment by shenwei356** [comment]
oh, right, it should be optional.

**Comment by shenwei356** [comment]
Added a flag.


      -f, --format-numbers   save numbers in number format, instead of text


[csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/10535404/csvtk_linux_amd64.tar.gz)
