### ISSUE TITLE
add-header in place

### ISSUE THREAD

**Issue by vkkodali** [shenwei356/csvtk#224]
This may be more of a question than an issue... 
I often come across situations where I have to either add or modify a header and prefer to do it in place without having to write the output to a new file. Is this possible? If not, can this be added as an option to `add-header`, `del-header`, `rename` and `rename2` commands?

**Comment by shenwei356** [comment]
In-place file edit are not easily supported. https://unix.stackexchange.com/questions/11067/is-there-a-way-to-modify-a-file-in-place

A common way is writinf to a new file, renaming and overwriting the old one.

**Comment by vkkodali** [comment]
Thanks, writing to a temporary file and copying it over the new one is what I am doing now. I guess I will just stick to that.
