### ISSUE TITLE
mark when record is truncated by `csvtk pretty` with `-W`

### ISSUE THREAD

**Issue by skywyx** [shenwei356/csvtk#228]
I think it's better to mark it when a record is truncated by `csvtk pretty` with `-W`.
e.g.
```
# cat test.csv
a,b,c
aa,bb,cc
aaa,bbb,ccc
```
when use cmd `cat test.csv|csvtk pretty -W 2` it's better to show as
```
a       b       c
--...   --...   --...
aa      bb      cc
aa...   bb...   cc...
```
just like it was shown with pandas

**Comment by shenwei356** [comment]
Thanks for your suggestion. It's easy to achieve by forking  https://github.com/tatsushid/go-prettytable/ and editing the function [truncateString](https://github.com/tatsushid/go-prettytable/blob/master/prettytable.go#L46).

But I might use other new method. #206

**Comment by shenwei356** [comment]
Implemented. Please check here: https://github.com/shenwei356/csvtk/issues/206#issuecomment-1609358555
