### ISSUE TITLE
How can two or more files be merged/joined with all data from both files kept?

### ISSUE THREAD

**Issue by xuhangliu** [shenwei356/csvtk#23]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

I would like to merge two or more files with all data from both files kept? However, it seems that csvtk join only allows unmatched data from the first file kept with -k parameter. More specifically, I would like to merge the following example data: 
username,phone
gri,11111
rob,12345
ken,22222
shenwei,999999

name,region
ken,nowhere
gri,somewhere
shenwei,another
Thompson,there

and get the following result:
username,phone,region
gri,11111,somewhere
rob,12345,NA
ken,22222,nowhere
shenwei,999999,another
Thompson,NA,there

How can I do it with csvtk? Thank you!

Xuhang

**Comment by shenwei356** [comment]
Sorry, not supported right now. 

I'll add this to TODO list.

**Comment by shenwei356** [comment]
@xuhangliu , sorry for such late implementation.::smile::
