### ISSUE TITLE
printing number 1 "out of the blue"

### ISSUE THREAD

**Issue by tompa911** [shenwei356/csvtk#232]
### Prerequisites

- [x ] make sure you're are using the latest version by `csvtk version`
- [ x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

brew info csvtk
==> csvtk: stable 0.26.0 (bottled), HEAD

execute the following
cat test.csv| csvtk pretty

output contains many unexpected lines containing only the number "1" which are not present in the input file
[test.csv](https://github.com/shenwei356/csvtk/files/11928588/test.csv)

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
Hi, The 1 is the last character 1 of wrapped sherlock51. You can either set a biger -n or -W.


https://bioinf.shenwei.me/csvtk/usage/#pretty

      -n, --buf-rows int            the number of rows to determine the min and max widths (default 128)
     -W, --max-width int           max width

**Comment by tompa911** [comment]
Very helpful, and quick answer. Thank you.
I didn't realize that -n exited. This solves my problem.
However ... I have the same processes running on macOS and Ubuntu Linux.
csvtk on Linux is v0.24.0 It formats the output as expected, no wrapping, without using any flags.
But that's OK. Just letting you know.

**Comment by shenwei356** [comment]
> csvtk on Linux is v0.24.0 It formats the output as expected, no wrapping, without using any flags.

Thanks for mentioning that. In [v0.26.0](https://github.com/shenwei356/csvtk/releases/tag/v0.26.0), I reimplemented the `pretty` command, which wraps long cells by default.
