### ISSUE TITLE
csvtk unselect range error

### ISSUE THREAD

**Issue by tolot27** [shenwei356/csvtk#234]
The range selector to "discard 1st to 3rd column" does not work as documented:

```
echo -e "1,2,3,4,5" | csvtk -H cut -f -1--3
[ERRO] invalid field range: -1--3. start (-1) should be less than end (-3)
```

It does not matter which numbers are used. It looks like the first dash is treated as the "minus" of the first number rather than as the unselect operater.

Both version 0.25 and 0.26 are affected.

**Comment by shenwei356** [comment]
Oh, both ways are supported now.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12028969/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12028971/csvtk_darwin_arm64.tar.gz)
-  [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12028972/csvtk_linux_amd64.tar.gz)



```
$ echo -e "1,2,3,4,5" | csvtk -H cut -f -1--3
4,5
$ echo -e "1,2,3,4,5" | csvtk -H cut -f -3--1
4,5
```
