### ISSUE TITLE
csvtk join does not allow duplicated column names

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#235]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

Hi, 
csvtk join does not allow duplicated column names as of version 0.26.0. This was ok in the previous version. 

Input table below gives the error: [ERRO] duplicate colnames not allowed: Allele
|Sample     |Scheme    |ST |Allele|Allele |Allele|Allele  |Allele |Allele  |Allele|
|:----------|:---------|:--|:-----|:------|:-----|:-------|:------|:-------|:-----|
|sample|cdifficile|8  |adk(1)|atpA(1)|dxr(2)|glyA(6) |recA(1)|sodA(5) |tpi(1)|

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
Sorry for this bug. I've changed the logic: only selected columns cannot be duplicated now.

- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12140689/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12140690/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12140686/csvtk_darwin_amd64.tar.gz)
