### ISSUE TITLE
Can you create a comand like spread that can many long line into group short lines with group as column names

### ISSUE THREAD

**Issue by NailouZhang** [shenwei356/csvtk#236]
### Prerequisites

Hi，
csvtk is a great work like dplyr and some software in R. csvtk is very simple and convenient without working in special language environments like R and python. As I know, It has gather command which can make short lines into long lines, but there is no command that can make long lines into short lines. I used to like pivot_longer and pivot_wider (https://tidyr.tidyverse.org/reference/pivot_longer.html) to do this conversion. But now I love into csvtk. 

Could you be nice to take some time to deal with this issue?

**Comment by shenwei356** [comment]
Yes, it should be useful. Someone advised this before as well. But I'm going to have my holiday, so I'll add it to the TODO list.

**Comment by shenwei356** [comment]
Implemented. see #91 and #239
