### ISSUE TITLE
Counting unique text occurences without empty cells

### ISSUE THREAD

**Issue by alvanuffelen** [shenwei356/csvtk#237]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

Is there a way to count unique text occurrences in a column without counting empty cells?
[example.txt](https://github.com/shenwei356/csvtk/files/12215435/example.txt)
```
cat example.txt | csvtk summary -f order:countuniq,family:countuniq,genus:countuniq,species:countuniq
order:countuniq,family:countuniq,genus:countuniq,species:countuniq
29,35,43,94
```

**Comment by shenwei356** [comment]
Oh, it's not supported. A work around solution:

```
for rank in order family genus species; do
    echo -ne “rank,$(csvtk cut -f $rank example.txt | csvtk uniq -f $rank | csvtk grep -r -v -p ^$ | csvtk nrows)\n";
done
```

**Comment by alvanuffelen** [comment]
Thanks, that worked!
Although, I had to change `“rank` to `"$rank`
