### ISSUE TITLE
del-header removes empty cells when the input is one column

### ISSUE THREAD

**Issue by alvanuffelen** [shenwei356/csvtk#238]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue
`csvtk del-header` on one column removes the empty cells.
[example.txt](https://github.com/shenwei356/csvtk/files/12226122/example.txt)

Empty cells are included:
```
cat example.txt | csvtk cut -f species
```
Empty cells are removed:
```
cat example.txt | csvtk cut -f species | csvtk del-header
```

**Comment by shenwei356** [comment]
Hmm, they are treated as empty rows and skipped since v0.26.0.

This is problematic in your situation, I should make it optional with

     -E, --ignore-empty-row       ignore empty rows

**Comment by shenwei356** [comment]
That's sad, the official csv reader skip blank lines by default, and no option to disable this.


https://pkg.go.dev/encoding/csv
>  Blank lines are ignored. A line with only whitespace characters (excluding the ending newline character) is not considered a blank line.

[Some guys tried to change this  but failed.](https://github.com/golang/go/issues/39119)

**Comment by shenwei356** [comment]
An workaround way: add the row number with the global flag `-Z/--show-row-num`, which would stop `del-header` remove blank lines

```
$ cat example.txt | csvtk cut -f species -Z | csvtk del-header | csvtk cut -f  -1 | wc -l
162

$ cat example.txt | wc  -l
163
```

**Comment by shenwei356** [comment]
It's sad that the standard package still do not fix this.
