### ISSUE TITLE
Problem running dynamically linked binary

### ISSUE THREAD

**Issue by celldee** [shenwei356/csvtk#24]
Hi,
Thanks for creating this very useful library. I have one observation which might help other users.
The binaries, that you helpfully provide for users, should be statically linked instead of dynamically linked to avoid problems with library paths.

I downloaded the Linux 64 bit binary but could not run it because of a library path mismatch for my distro (NixOS). When I created a statically linked binary it ran successfully.

Regards,
Chris

**Comment by shenwei356** [comment]
Hi Chris, the binaries are indeed statically linked. The linux 64 bit binary should work in most distros. It is likely because of the unique packagee management of NixOS, I guess.

**Comment by celldee** [comment]
Hi,
The reason why I say the binary that I was trying to use is dynamically linked is because of the output that I got from the file command. When I run the file command against the csvtk binary that I extracted from csvtk_linux_amd64.tar.gz (file csvtk), I see the following output -
`csvtk: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped`

However, when I run the same file command against the binary I created from your source, I see the following output -

`csvtk: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped`

The command that I used to create my golang binary was -

`env CGO_ENABLED=0 GOOS=linux go build -a -tags netgo -ldflags '-w'`

The binary that I created runs on my system, however, the binary that I downloaded does not because the path /lib64/ld-linux-x86-64.so.2 does not exist on my system.

Regards,
Chris
