### ISSUE TITLE
csvtk mutate2 version 0.27.0 gives errors when use column numbers

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#242]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

Hi, something has been changed in `csvtk mutate2 `version 0.27.0. It gives errors when use column names 

```
$ echo -e "one,two\na1,a2\n,b2\na2,"     | csvtk mutate2 -n three -e '$one ?? $two'     | csvtk pretty
one   two   three
---   ---   -----
a1    a2    a1   
      b2    b2   
a2          a2 
```

```
$ echo -e "one,two\na1,a2\n,b2\na2,"     | csvtk mutate2 -n three -e '$1 ?? $2'     | csvtk pretty
[ERRO] data: [a1 a2], err: No parameter 'shenwei1' found.
[WARN] csvtk pretty: skipping empty input file: -
```

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
ouch ~ 

fixed.

- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12344919/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12344920/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12344917/csvtk_darwin_amd64.tar.gz)

**Comment by MostafaYA** [comment]
Thanks! It worked.

Another question: how can mutate2 accept column name with space. 

Here is an example

```
$ echo -e "one,two\na1,a2\n,b2\na2,"   \
  | csvtk rename -n "one one" -f 1  \
  | csvtk mutate2 -n three -e '$1 ?? $2'  \
  | csvtk pretty

one one   two   three
-------   ---   -----
a1        a2    a1   
          b2    b2   
a2              a2   
```
This does not work!
```
echo -e "one,two\na1,a2\n,b2\na2," \
 | csvtk rename -n "one one" -f 1 \
 | csvtk mutate2 -n three -e '$"one one" ?? $two'  \
 | csvtk pretty

[ERRO] Invalid token: '$'
[WARN] csvtk pretty: skipping empty input file: -
```

**Comment by shenwei356** [comment]
`${one one}`
