### ISSUE TITLE
Shortcut for the flag --infile-list?

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#249]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

Hi, I use csvtk as part of a pipeline and it often happens that I can pass hundreds or thousands of files to csvtk via the command line. This causes csvtk to crash. The `--infile-list` is a nice addition that overcomes this issue. May you consider any shortcut for this flag: `--infile-list` 
### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
`i`, `I`, `l` and `L` all conflict with existing flags. `X` would be the one.

**Comment by shenwei356** [comment]
```
  -X, --infile-list string     file of input files list (one file per line), if given, they are appended
                               to files from cli arguments
```
