### ISSUE TITLE
[ERRO] open /tmp/excelize-3074771143: no such file or directory

### ISSUE THREAD

**Issue by tchiavegatti** [shenwei356/csvtk#251]
I got an error when I tried to convert an XLSX file to CSV:

```bash
csvtk xlsx2csv excelfile.xlsx -n Sheet1 > output.csv
[ERRO] open /tmp/excelize-969081702: no such file or directory
```

The number after `/tmp/excelizes` changes, but I always get the same error. I tried to run it on Linux (WSL2) and on Windows, but the result is the same:

```powershell
# Windows - Powershell
Get-ChildItem $datadir -File -Filter '*.xlsx' | ForEach-Object {.\csvtk.exe xlsx2csv $_.FullName -n "Sheet1"}
[ERRO] open C:\Users\username\AppData\Local\Temp\excelize-877759494: The system cannot find the file specified.
```

**Comment by shenwei356** [comment]
That's weird. Which version are you using? Try the latest version, please. I've confirmed it works as expected on Windows 10.

[csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12620648/csvtk_linux_amd64.tar.gz)
[csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/12620650/csvtk_windows_amd64.exe.tar.gz)

**Comment by tchiavegatti** [comment]
```bash
csvtk version
csvtk v0.27.2
```

**Comment by shenwei356** [comment]
Is the .xlsx file large? It looks like the `excelize` packages do [use tmp files](https://github.com/search?q=repo%3Aqax-os%2Fexcelize%20excelize-&type=code), but when it uses is not clear.

**Comment by tchiavegatti** [comment]
Around 30MB, 215,000 lines.

**Comment by shenwei356** [comment]
It's fixed.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12654476/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12654479/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12654481/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/12654484/csvtk_windows_amd64.exe.tar.gz)
