### ISSUE TITLE
Column headers do not respond to flags set to position new columns in mutate2 cmd

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#252]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

csvtk version v0.27.2

column headers do not respond to flags `--at` `--after` or `--before` in the `mutate2` command

Here is the example from the manual

```
echo -ne "a,b,c\n1,2,3\n" | csvtk mutate2 -e '$a+$c' -n x -w 0 --at 1
a,b,c,x
4,1,2,3
```
### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
Oh, sorry about that, the code was accidentally missing during code refactoring in v0.27.0.

```
$ echo -ne "a,b,c\n1,2,3\n" | csvtk mutate2 -e '$a+$c' -n x -w 0 --at 1
x,a,b,c
4,1,2,3

$ echo -ne "a,b,c\n1,2,3\n" | csvtk mutate2 -e '$a+$c' -n x -w 0 --after b
a,b,x,c
1,2,4,3

$ echo -ne "a,b,c\n1,2,3\n" | csvtk mutate2 -e '$a+$c' -n x -w 0 --before b
a,x,b,c
1,4,2,3
```
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12654345/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12654342/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12654343/csvtk_darwin_arm64.tar.gz)

**Comment by MostafaYA** [comment]
Thanks!

**Comment by tolot27** [comment]
This problem is still not fixed with external variables introduced with #37.

```bash
val=ABC; echo -ne "a,b,c\n1,2,3\n" | csvtk mutate2 -e " '$val' " -n x --at 1
a,b,c,x
1,2,3,ABC
```

**Comment by shenwei356** [comment]
Thanks for reporting this. Previously, when the expression only contained constant strings or numbers, another simple workflow was used, in which I forgot to apply the position to insert.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/13389370/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/13389371/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/13389372/csvtk_linux_amd64.tar.gz)
