### ISSUE TITLE
header names for new columns created with 'summary'

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#254]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

Hi, may you consider changing ":" with "_" for the auto generated column headers after running some commands like `summary` because I thinks it conflicts with other commands when piping the output and I have to correct this with `rename` .

here is an example 

```bash
cat test
f1,f2,f3,f4,f5
foo,bar,xyz,1,0
foo,bar2,xyz,1.5,-1
foo,bar2,xyz,3,2
foo,bar,xyz,5,3
foo,bar2,xyz,N/A,4
bar,xyz,abc,NA,2
bar,xyz,abc2,1,-1
bar,xyz,abc,2,0
bar,xyz,abc,1,5
bar,xyz,abc,3,100
bar,xyz2,abc3,2,3
```
```bash 
cat test | csvtk summary -g f1,f2  -f f5:median | csvtk sort -k "f5:median":nr
[ERRO] invalid sort type: median}
```

This however works 

```bash 
cat test | csvtk summary -g f1,f2  -f f5:median | csvtk sort -k 3:nr
```
* may be you can allow users to choose the header name they want

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
I make `csvtk sort` supporting column names containing colons.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12698184/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12698190/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12698194/csvtk_linux_amd64.tar.gz)

```
$ cat test | csvtk summary -g f1,f2  -f f5:median -i | csvtk sort -k "f5:median":nr | csvtk pretty 
f1    f2     f5:median
---   ----   ---------
bar   xyz2   NaN      
foo   bar2   2.00     
bar   xyz    2.00     
foo   bar    1.50
```
