### ISSUE TITLE
Cannot run Windows 32-bit or 64-bit builds of version 0.28.0 on Windows 10 x64

### ISSUE THREAD

**Issue by excel4** [shenwei356/csvtk#256]
### Prerequisites

version 0.28.0 release

### Describe your issue
I am not able to run the release builds for versions 0.28.0 for Windows 32-bit or 64-bin on a Windows 10 x64 system. The system reports:

"This version of csvtk_windows_028_amd64.exe is not compatible with the version of Windows you
are running. Check your computer's system information and then contact the software publisher."

I tried running the 386 build in the Programs x86 directory and it reported that the program is a 16-bit application.

I also tried both versions on an older windows 7 system and the same problem occurred.

Is there some configuration required to run these binaries on Windows 10 x64 (intel i7)?

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
Just tested it, and it works as expected.

![image](https://github.com/shenwei356/csvtk/assets/2655946/4bd4763b-28b9-479d-9dae-5062a672c579)

I also tried to double-click the .exe files, but it showed other information, not the one you pasted.

We did not provide files named `csvtk_windows_028_amd64.exe`, could you please re-download one again?

**Comment by excel4** [comment]
I re-downloaded the file and the same thing happened. I think the renaming has to do with process 7zip uses. The file says it is a tar.gz file, but 7zip says it is just a gzip file. I was able to download and extract it as csvtk.exe and it still fails. The executable I downloaded is:
21,575,680  bytes
MD5: 76bcab9b6d145d9d9a35abeee19630c7
sha256: 2da67ade1c906f36cd9925d7e8adfe6f4ed27ffeba9f650a8132421f7812ba56,

I am running this on a Windows 10 machine with an Intel i7 processor. The file says that is "AMD64", which may be the issue. Is it built for an AMD architecture? I do not see an "X64" or "X86-64" version of the build. Perhaps there are some hardware specific features in the compiled build.

When you build the system is there an option to build it for "X64 or X86-64" architecture?

![csvtk1](https://github.com/shenwei356/csvtk/assets/7359678/c0d1ac83-f0d5-4ec2-85cd-ce6dcfef706b)

**Comment by shenwei356** [comment]
> I think the renaming has to do with process 7zip uses. The file says it is a tar.gz file, but 7zip says it is just a gzip file. 

You find the cause! You should use other tools to decompress it. Or try another format: [csvtk.zip](https://github.com/shenwei356/csvtk/files/13199012/csvtk.zip)

```
$ md5sum csvtk.exe
00cb5415dc92d66502d73b960d487c68  csvtk.exe

$ md5sum csvtk_windows_amd64.exe.tar 
76bcab9b6d145d9d9a35abeee19630c7  csvtk_windows_amd64.exe.tar
```

^ see here, you're running the tarball file :sweat_smile:


About `amd64`:

> x86-64 (also known as x64, x86_64, AMD64, and Intel 64)
> https://en.wikipedia.org/wiki/X86-64

**Comment by excel4** [comment]
Thanks much for clarifying the file hashes. The downloaded file was being renamed as a  ".exe" vs. a ".tar" fille. I was able to extract the .exe file and it works fine. 

Thanks for your help and apologies for the inconvenience.

**Comment by excel4** [comment]
Thanks much for clarifying the file hashes. The downloaded file was being renamed as a ".exe" vs. a ".tar" fille. I was able to extract the .exe file and it works fine.

Thanks for your help and apologies for the inconvenience.
