### ISSUE TITLE
del-header removes the header from only the first CSV file in a list of multiple CSV file name arguments.

### ISSUE THREAD

**Issue by derekmahar** [shenwei356/csvtk#257]
[`csvtk del-header`](https://bioinf.shenwei.me/csvtk/usage/#del-header) removes the header from only the first CSV file in a list of multiple CSV file name arguments.

```
$ \cat 0000001.csv 0000002.csv
Column
1
Column
2
$ csvtk del-header 0000001.csv 0000002.csv
1
Column
2
```

### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
```
$ csvtk version
csvtk v0.28.0
```
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

See [`csvtk del-header`](https://bioinf.shenwei.me/csvtk/usage/#del-header).

### Describe your issue

* [x] describe the problem

* [x] provide a reproducible example

**Comment by shenwei356** [comment]
Thanks for reporting this. I didn't even consider this.

- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/13272224/csvtk_darwin_arm64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/13272227/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/13272229/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/13272230/csvtk_windows_amd64.exe.tar.gz)

**Comment by derekmahar** [comment]
Thank you for fixing this issue so quickly!

**Comment by derekmahar** [comment]
I confirm that `csvtk del-header` in csvtk 0.28.1 removes the header from all CSV files specified as arguments.

```
$ csvtk version
csvtk v0.28.1
$ \cat 0000001.csv 0000002.csv 0010000.csv
Column
1
Column
2
Column
10000
$ csvtk del-header 0000001.csv 0000002.csv 0010000.csv
1
2
10000
$ find . -type f -name "*.csv" | sort | head -n 10000 | xargs csvtk del-header | grep Column | wc -l
0
```
