### ISSUE TITLE
Global flag '-q --quiet'?

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#261]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue
Hi, 
to suppress warning messages, how about the '--quiet' flag? 
Messages may be annoying when passing data to cascades of csvtk subcommands

* [ ] describe the problem
* [ ] provide a reproducible example

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
added.

**Comment by MostafaYA** [comment]
Thanks a lot. If possible, would you please publish this version 0.30 in conda - thanks again

**Comment by shenwei356** [comment]
https://github.com/shenwei356/csvtk/releases/tag/v0.30.0
