### ISSUE TITLE
leading zeros are deleted in xlsx2csv command

### ISSUE THREAD

**Issue by 5003** [shenwei356/csvtk#262]
Hi,
When converting with the following versions, leading zeros are deleted.

- 0.27.2
- 0.28.0
- 0.29.0

File: [test data](https://github.com/5003/test-20231203_csvtk_xlsx2csv_issue/blob/main/000_cell_data.xlsx)
Command: `csvtk xlsx2csv -n example 000_cell_data.xlsx`

Output:

```
txt
0

```

Version 0.27.1 does not have this problem.

**Comment by shenwei356** [comment]
Thanks for reporting this. 
It's fixed.

```
$ csvtk xlsx2csv -n example 000_cell_data.xlsx
txt
000
```

[csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/13540324/csvtk_darwin_amd64.tar.gz)
[csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/13540325/csvtk_darwin_arm64.tar.gz)
[csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/13540326/csvtk_linux_amd64.tar.gz)
[csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/13540327/csvtk_windows_amd64.exe.tar.gz)

**Comment by 5003** [comment]
It works.
Thank you.

**Comment by moorereason** [comment]
I believe #262 fixes a related issue I had after upgrading from v0.28.0 to v0.29.0:

```
csvtk xlsx2csv $foo | csvtk mutate2 -n Debit -w 0 -e '$Total * 100'
```
would generate an error:

> err: Value '$175.00' cannot be used with the modifier '*', it is not a number

The cell in the Excel spreadsheet is a formula of type Currency.

After rebuilding from master (22723a7b46c17b33d8061e2f7820356a32bb175e), the issue is resolved.
