### ISSUE TITLE
bug: spurious points in plots

### ISSUE THREAD

**Issue by janxkoci** [shenwei356/csvtk#279]
First, thank you for this handy tool! I especially love the plotting feature, but I've encountered a problem, where I often have spurious extra points in my plots.

## reproducible example
The issue is already visible using this toy example:

```
seq 1 10 | awk '{print $1, $1}' OFS="," | csvtk -H plot line -x 1 -y 2 > csvtk_plot_bugreport.png
```

The code above produces the following plot:

![csvtk_plot_bugreport](https://github.com/shenwei356/csvtk/assets/19331850/9a1cf10a-1079-4b32-8edb-da1b361a17cf)

Note that the plot has a point in lower-right corner that should not be there.

Another issue is that the line gets all zig-zaggy if the input is not sorted on the column being plotted (I can report it as separate issue later, as I don't have a good reproducer now).

It would be also cool to support groupping in line plots, so that different series of data could be plotted together using different colours and symbols (like the first example from [gonum/plot wiki](https://github.com/gonum/plot/wiki/Example-plots)). Also `box` could support colours for groups of boxes (based on some factor), but the UX may need some thought, as `-g` is already used for grouping the values for the individual boxes. Again, I can submit these as separate feature requests later, if you prefer.

## version
I just updated from 0.29 to 0.30, using bioconda, and the issue is in both versions (my OS is Linux).

**Comment by janxkoci** [comment]
Ok I'm dumb - I just realized the extra point is actually a legend 🤦 However it never has labels so it never occurred to me before. How do I add category label to it?

**Comment by shenwei356** [comment]
`csvtk plot` has a global option:

```
  -g, --group-field string     column index or column name of group
```

```
(seq 1 10 | awk '{print "a", $1, $1  }' OFS=","; \
 seq 1 10 | awk '{print "b", $1, $1+1}' OFS=",";) \
| csvtk -H plot line -x 2 -y 3 -g 1
```

![image](https://github.com/shenwei356/csvtk/assets/2655946/a57d5d01-7ba0-447d-9f17-18730aa86849)

**Comment by janxkoci** [comment]
Ok, I really misunderstood the feature, the issue can be closed.

One last question: Is there a way to disable the legend? For the cases when there is just one series. It can also be useful when we want to combine multiple plots with one shared legend (e.g. with `imagemagick montage`).

**Comment by shenwei356** [comment]
Here they are:
    
- [csvtk_darwin_amd64.tar.gz](https://github.com/user-attachments/files/15945506/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/user-attachments/files/15945507/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/user-attachments/files/15945508/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/user-attachments/files/15945509/csvtk_windows_amd64.exe.tar.gz)

The same example:

    seq 10 | csvtk mutate -H | csvtk -H plot line -x 1 -y 2 -o t.png

![t](https://github.com/shenwei356/csvtk/assets/2655946/f73c3cd8-69a6-408a-8e52-f3b0b45ce5e8)

**Comment by janxkoci** [comment]
Is this a new release? I install csvtk with conda to have consistent versions across my computers.

**Comment by shenwei356** [comment]
no, just a pre-release, it should be 0.30.1, I didn't change it .
