### ISSUE TITLE
sort x before plot line

### ISSUE THREAD

**Issue by janxkoci** [shenwei356/csvtk#280]
I noticed a problem with line plots and found that it can be easily solved by pre-sorting data used for X axis. Since no other package or plotting library (like R `base` or `ggplot2`) asks me to sort data before plotting, I think it should be done automatically also in `csvtk`.

## reproducible examples
First, let's generate some example data:

```
$ seq 1 10 | sort -R | awk '{print $1 "," NR}' > csvtk_plot_xorder_bug.csv
$ cat csvtk_plot_xorder_bug.csv
9,1
5,2
7,3
1,4
2,5
6,6
4,7
10,8
3,9
8,10
```

Now, we can try some plots.

### wrong plots
Using the following code:

```
csvtk -H plot line -x 1 -y 2 csvtk_plot_xorder_bug.csv > csvtk_plot_xorder_xunsorted.png
```

we get this plot:

![csvtk_plot_xorder_xunsorted](https://github.com/shenwei356/csvtk/assets/19331850/5f2b31c6-f47c-4152-a430-3cd7989e4c07)

That's obviously wrong. But it still happens to be sorted by the Y axis - we can mess it up even more with random sort using the following code:

```
sort -R csvtk_plot_xorder_bug.csv | csvtk -H plot line -x 1 -y 2 > csvtk_plot_xorder_xrandom.png
```

![csvtk_plot_xorder_xrandom](https://github.com/shenwei356/csvtk/assets/19331850/78a881c7-1cac-4bd5-94ee-ec438dcaf5fc)

### good plot
The solution is to just sort the data on X axis before plotting:

```
csvtk -H sort -k 1:n csvtk_plot_xorder_bug.csv | csvtk -H plot line -x 1 -y 2 > csvtk_plot_xorder_xsorted.png
```

And the result:

![csvtk_plot_xorder_xsorted](https://github.com/shenwei356/csvtk/assets/19331850/b8621a30-ef0a-4477-a73f-10f243b02e2e)

This is much nicer and should be done by default whenever we want to make line plots, just like R or `ggplot2` do.

### notes
Originally, I came across the issue when making real plots such as this one:

![sgdp_nd1x](https://github.com/shenwei356/csvtk/assets/19331850/91bed827-04db-47ea-b33f-82396f46eb11)

Only much later I found sorting the data fixes the issue, which was not obvious, so I instead had to resort to scatterplots, which are not always good fit.

**Comment by shenwei356** [comment]
Sorry, I forgot to fix this ~
