### ISSUE TITLE
fix-quotes: [ERRO] bufio.Scanner: token too long

### ISSUE THREAD

**Issue by joverlee521** [shenwei356/csvtk#283]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

As a follow up to https://github.com/shenwei356/csvtk/issues/130, I am trying to wrap `csvtk` pipelines with `fix-quotes` and `del-quotes` when working with TSVs, but I'm running into an error with `fix-quotes`:

```
[ERRO] bufio.Scanner: token too long
```

Seems like this error was previously reported for `space2tab` in https://github.com/shenwei356/csvtk/issues/231. 
Can the same `-b, --buffer-size` flag be added to `fix-quotes`? 

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
It's fixed: https://github.com/shenwei356/csvtk/commit/ee688fb7e058cc6acd6f0719a35e5ffacd35fb16

Please use binaries here: https://github.com/shenwei356/csvtk/issues/282
