### ISSUE TITLE
Use bash variable in filter2 --filter expression

### ISSUE THREAD

**Issue by andrewmackenzie** [shenwei356/csvtk#284]
I'm trying to use a bash variable in the --filter expression for the filter2 command. LIke this:

`var1="abc" ; csvtk filter2 --filter '$column_name=="$var1"' < /Users/andrew/thefile.csv`

but I get "column "var1" not existed in file:" error. How do I pass a bash variable into the --filter expression?

**Comment by shenwei356** [comment]
```
val="x"; echo -ne "a,b\n1,y\n0,x\n" | csvtk filter2 -f "\$b == \"$val\""
a,b
0,x

```

`csvtk filter2` is very slow. `csvtk grep` is recommended for matching the whole cell value.

```
$ val="x"; echo -ne "a,b\n1,y\n0,x\n" | csvtk grep -f b -p $val
a,b
0,x
```

**Comment by andrewmackenzie** [comment]
That's exactly what I needed. Thanks!
