### ISSUE TITLE
Sort empty CSV without ERROR ?

### ISSUE THREAD

**Issue by tetedange13** [shenwei356/csvtk#287]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)
<br>

### Describe your issue

It is rather a question

Current behaviour of `csvtk sort` on an empty CSV is to return an non-0 exit code with `[ERRO] no data to sort`

Do you think it would be a good idea to rather **not** ERROR, but simply return same CSV with a `[WARN]` instead ?

This is already the behaviour of `csvtk freq` for example :
```bash
echo -e "c1,c2" | csvtk sort
# -> [ERRO] no data to sort

echo -e "c1,c2" | csvtk freq
# -> c1,frequency
```
<br>

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

***Thanks to YOU for developping `csvtk`, it is a great tool !***

**Comment by shenwei356** [comment]
Sorry for the late reply. It's fixed.

```
$ echo -e "c1,c2" | csvtk sort
[WARN] no data to sort from file: -
c1,c2

$ echo | csvtk sort
[WARN] no data to sort from file: -

$ echo -ne '' | csvtk sort
[WARN] csvtk sort: skipping empty input file: 
```

**Comment by shenwei356** [comment]
Use the binaries here: https://github.com/shenwei356/csvtk/issues/288#issuecomment-2418375162
