### ISSUE TITLE
csvtk split into subfolder structure

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#288]
This may already be doable, but I couldn't find out how.

I want to use `csvtk split` to produce N number of .csv files splitting by the column barcode, which is a 16-mer of A,T,C, and Gs.

Given my input files, this operation can produce 20,000 or more output files, which all would go in the same output directory, 

I'd like to be able to split the output files into subfolders, so that on average, each subfolder will only receive a fraction of output files, which makes this behave better in certain filesystems in Linux (some slow down after more than 1024 files, some after 4096 files). For example, for a 16-mer barcode, it would be useful for csvtk split to produce kmer=3 subfolders.

E.g.:

```
csvtk split -f barcode file.csv --kmer-subdir 3
```

If we have the following barcodes:
ATC...
TCG...
GTA...

They would end up in subfolders:

```
ATC/{ATCNNNNNNNNNNNNN}.csvs only the csvs with the field starting with ATC
TCG/{TCGNNNNNNNNNNNNN}.csvs, etc
GTA/{GTANNNNNNNNNNNNN}.csvs, etc.
```

Thanks in advance,

**Comment by shenwei356** [comment]
implemented.

- [csvtk_darwin_amd64.tar.gz](https://github.com/user-attachments/files/17405298/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/user-attachments/files/17405302/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/user-attachments/files/17405303/csvtk_linux_amd64.tar.gz)


Example:

    $ echo -ne "1,ACGT\n2,GGCA\n3,ACAAC\n"
    1,ACGT
    2,GGCA
    3,ACAAC

    $ echo -ne "1,ACGT\n2,GGCA\n3,ACAAC\n" | csvtk split -H -f 2 -o t -p "" -s 3 --force

    $ tree t
    t
    ├── ACA
    │   └── ACAAC.csv
    ├── ACG
    │   └── ACGT.csv
    └── GGC
        └── GGCA.csv

    4 directories, 3 files
