### ISSUE TITLE
csvtk cut   Error: unknown shorthand flag: 'i' in -i

### ISSUE THREAD

**Issue by lhmjyhlh** [shenwei356/csvtk#29]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [ ] provide a reproducible example

Test code 

    cat seqIDvsChrName.txt | csvtk cut -f -F "chr*" -i 

Error: unknown shorthand flag: 'i' in -i

**Comment by lhmjyhlh** [comment]
similar results for this code：

cat seqIDvsChrName.txt | csvtk cut -f -F -i "chr*"

**Comment by shenwei356** [comment]
it's not an error, it's just not supported.

**Comment by shenwei356** [comment]
Available in [0.9.2-dev2](https://github.com/shenwei356/csvtk/releases/tag/v0.9.2-dev2)
