### ISSUE TITLE
csv2json issues

### ISSUE THREAD

**Issue by datatraveller1** [shenwei356/csvtk#291]
### Prerequisites

version: csvtk v0.30.0

### Describe your issue
I have noticed four issues with the **csv2json** command.

command:  `csvtk csv2json testdata.csv -o testdata.json`

`input file testdata.csv`:
test
none
"Make America ""great"" again"
\nations
"This is a
MULTILINE
string"

`actual output file testdata.json`: 
```
[
  {
    "test": null
  },
  {
    "test": "Make America "great" again"
  },
  {
    "test": "\nations"
  },
  {
    "test": "This is a
MULTILINE
string"
  }
]
```

`expected output file testdata.json`:
```
[
  {
    "test": "none"
  },
  {
    "test": "Make America \"great\" again"
  },
  {
    "test": "\\nations"
  },
  {
    "test": "This is a\nMULTILINE\nstring"
  }
]
```
`Comments`:

- issue 1: I want "none" to be depicted literally and neither changed to "null" (no option) nor "" (empty string with option -b)

- issue 2: In JSON, double quotes have to be escaped with a backslash (`\"`)

- issue 3: In JSON, backslashes have to be escaped with a backslash (`\\`)

- issue 4: In JSON, the line breaks of a CSV multiline cell have to be depicted as `\n`

### Thank you

Thank you very much for the great csvtk tool!

**Comment by shenwei356** [comment]
OK, fixed, and it will be available in the next release.

```
$ go build && cat testdata.csv | ./csvtk csv2json -b
[
  {
    "test": "none"
  },
  {
    "test": "Make America \"great\" again"
  },
  {
    "test": "\\nations"
  },
  {
    "test": "This is a\nMULTILINE\nstring"
  }
]

```

**Comment by datatraveller1** [comment]
Great thank you, very much! I can confirm it works fine on MS Windows with version 0.31.0.
`LF` and `CRLF` get changed to `\n`  which is the best solution both for Linux and Windows.

A small note for the next version, although this is very rare in practice:
A `tab` character inside the CSV should be changed to "`\t`" in JSON.
Thank you again.

**Comment by shenwei356** [comment]
Thanks, I'll add these later.
