### ISSUE TITLE
csvtk cut with fields 1-3 and fuzzy matching issues

### ISSUE THREAD

**Issue by colindaven** [shenwei356/csvtk#293]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [ ] provide a reproducible example

I am trying to read fields 1-3 and fuzzy match *chr2* (there are many cols containing chr2) in the file. Is this legal or not supported, or do I need to write the cut command differently. Thanks!

 ```
 csvtk cut -t -F -f 1-3,"*chr2*" pavs.matrix.tsv > test.tsv


  [ERRO] failed to parse *chr2* as a field number, you may mix the use of field numbers and column names
```

**Comment by shenwei356** [comment]
It's not supported, column fields and column names can't be mixed-used. 

Please consider replacing `1-3` with specific column names.

**Comment by colindaven** [comment]
Thanks, that did the trick
