### ISSUE TITLE
filter2 in csvtk 0.31.1

### ISSUE THREAD

**Issue by fengyuchengdu** [shenwei356/csvtk#295]
It seems that this update of filter2 broke something during interpreting the logic expression "&&", whereas csvtk 0.31.0 worked well on the same dataset.

**Comment by fengyuchengdu** [comment]
I did some test and seems that the order of column matters in 0.31.1 now. Swapping columns id and first_name to see if it still works.

**Comment by fengyuchengdu** [comment]
csvtk filter2 -f '$B == 0 && $A >= 20' example.csv | csvtk pretty
strain            B   A         
---------------   -   ----------
GCA_000149305.1   0   77.7364887

csvtk filter2 -f '$A >= 20 && $B == 0' example.csv | csvtk pretty
strain   B   A
------   -   -

**Comment by shenwei356** [comment]
I see, it's a bug, I'll fix it soon.

**Comment by shenwei356** [comment]
fixed.

- [csvtk_darwin_arm64.tar.gz](https://github.com/user-attachments/files/17975392/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/user-attachments/files/17975386/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/user-attachments/files/17975388/csvtk_windows_amd64.exe.tar.gz)

**Comment by tseemann** [comment]
Just to confirm this will fix `mutate2 -e` also?

**Comment by shenwei356** [comment]
Fixed in https://github.com/shenwei356/csvtk/releases/tag/v0.32.0
