### ISSUE TITLE
csvtk on Arch Linux

### ISSUE THREAD

**Issue by clintval** [shenwei356/csvtk#30]
Hi! Thanks for the useful tool, started using it today.

Just wanted to let you know I am maintaining a package for this utility for anyone on Arch Linux here: https://aur.archlinux.org/packages/csvtk/

Anyone using an Arch OS can install with their package manager now.

Feel free to close, just wanted to inform you!

**Comment by shenwei356** [comment]
Thank you! I'll add it to the installation section.

**Comment by shenwei356** [comment]
added: https://github.com/shenwei356/csvtk/commit/b8620acb5dffc75c049c8c7e0d0ddfdb89a98d72

**Comment by clintval** [comment]
Thanks!
