### ISSUE TITLE
handle BOM

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/csvtk#33]
https://github.com/shenwei356/multicorecsv

https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by shenwei356** [comment]
available after https://github.com/shenwei356/csvtk/commit/ea9b721770e0c7f8050aedaf03f5e6975a8cdd36 by updating (https://github.com/shenwei356/xopen/commit/41c04315b4376ad248d8bf0b0696aa713932b6d2)

**Comment by VladimirAlexiev** [comment]
@shenwei356 Can I reopen this?
```
>od -c -N 20 2022_01_ActualGenerationOutputPerGenerationUnit_16.1.A.csv
0000000 357 273 277   D   a   t   e   T   i   m   e  \t   R   e   s   o
0000020   l   u   t   i

>csvtk summary -f DateTime -g ResolutionCode 2022_01_ActualGenerationOutputPerGenerationUnit_16.1.A.csv
[ERRO] column "DateTime" not existed in file: 2022_01_ActualGenerationOutputPerGenerationUnit_16.1.A.csv

>csvtk version
csvtk v0.24.0

>uname
CYGWIN_NT-10.0
```
Let me know how I can help you diagnose this!

**Comment by shenwei356** [comment]
Missing `-t` for a tab-delimited file.

**Comment by VladimirAlexiev** [comment]
You must be provident! I was misled by the file name and didn't check inside. Thanks!

**Comment by shenwei356** [comment]
I checked the code and spent a few minutes to generate such a file and tested on a Windows VM, but everything is all right 😳 

Finally, it's the delimiter 😅
