### ISSUE TITLE
use mutate2 to add new column(s) based on bash variables

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#37]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue
I am trying to use mutate2 to add a column or series of columns but based on values from my bash command-line. E.g. this does not work as it does not pick up the value of the bash variable $val:
> 
val=RUN515 && cat testdata/region.csv | csvtk mutate2 -n run_id -e '1 > 0 ? "${val}" : "${val}"'

The context in which I am doing this is that I have a bunch of worksheets on an xlsx, and I want to aggregate them together, but add some extra columns for each of them (runid) that I can pass as bash variables like in the example below ($runid is the name of each worksheet):

> csvtk xlsx2csv -n RUNLIST $meta | grep completed | csvtk cut -T -f 1,7 | xargs -n2 echo | while read runid runcomplete; do csvtk xlsx2csv -n $runid $meta | head -n19 | csvtk transpose -; done

My thinking was that I could pass the bash variable $runid to the `csvtk mutate2` command somehow, e.g.:

> csvtk xlsx2csv -n RUNLIST $meta | grep completed | csvtk cut -T -f 1,7 | xargs -n2 echo | while read runid runcomplete; do csvtk xlsx2csv -n $runid $meta | head -n19 | csvtk transpose - | csvtk mutate2 -n run_id -e ' 1 > 0 ? $runid : $runid'; done

Any ideas?

**Comment by shenwei356** [comment]
You can `mutate` (not mutate2) and `replace` added last column with `$val`.

I'll test more simple method when using computer.

**Comment by avilella** [comment]
Fantastic. This works wonders. Thanks!

**Comment by shenwei356** [comment]
Hi Albert @avilella , here's a simpler method using [v0.13.0-dev2](https://github.com/shenwei356/csvtk/releases/tag/v0.13.0-dev2) or later versions:

```
$ val=ABC && seq 3 | csvtk mutate2 -H -e " '$val' "
1,ABC
2,ABC
3,ABC
```

**Please pay attention to the quotes**, double-quotes must be outside so the value of shell variable can be parsed, and the inner single quote is for making the value of $val a string constant which is required by the eval expression.

**Comment by avilella** [comment]
Brilliant, thanks. This is indeed a simpler way.
