### ISSUE TITLE
collate / concatenate / aggregate sets of files with identical fields

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#38]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

I have a collection of worksheets in an xlsx file, each worksheet should be of the same type. I want to collate them together (or concatenate or aggregate, not sure what the best word is), so that the order in which I concatenate them is preserved, but the duplicated headers disappear. I am currently doing this with `datamash rmdup 1` below, but I rather have a pure csvtk recipe for this:

> 
csvtk xlsx2csv -n LISTOFWORKSHEETS $meta | csvtk cut -f1 | while read ws; do csvtk xslx2csv -n $ws $meta; done | datamash rmdup 1 -t ',' > final_collated_file.csv

What would be the recipe for this collate operation in csvtk? Thanks in advance.

**Comment by shenwei356** [comment]
I'll add a `concat` command. 

```
for f in *.xlsx; do csvtk xls2csv $f > $f.csv; done

csvtk concat *.xlsx.csv > final.csv
```

**Comment by shenwei356** [comment]
`csvtk concat` is available in [v0.13.0-dev](https://github.com/shenwei356/csvtk/releases/tag/v0.13.0-dev) or later versions.

You can use command:

    csvtk xlsx2csv -n LISTOFWORKSHEETS $meta \
        | csvtk cut -f1 \
        | while read ws; do \
            csvtk xslx2csv -n $ws $meta > $meta.$ws.csv ; \
          done;
    csvtk concat *.csv > final_collated_file.csv

**Comment by avilella** [comment]
Fantastic! Thank you.

**Comment by shenwei356** [comment]
You're welcome. Please share with others if you find `csvtk` useful. :smile:
