### ISSUE TITLE
Always 'bad file descriptor ' on OSX

### ISSUE THREAD

**Issue by linkdesu** [shenwei356/csvtk#4]
I install csvtk_darwin_amd64.tar.gz on my OSX 10.11.6 and get the error below :

```
csvtk stat query_result.csv
[ERRO] read query_result.csv: bad file descriptor
```

Is there any thing wrong ?

**Comment by shenwei356** [comment]
Hi, I check the source code and every thing seems fine. I don't have a Mac right now, I'll reply later.

**Comment by shenwei356** [comment]
Hi @linkdesu , someone using OSX 10.11.6 has csvtk working fine. You may check the file.

**Comment by linkdesu** [comment]
Sorry for replying late, I found it is because my csv is in wrong format, some col which is html contains `\n` and break the line .
