### ISSUE TITLE
I am having trouble with using csvtk concat ; Error: unknown command "concat" for "csvtk"

### ISSUE THREAD

**Issue by jmsegret** [shenwei356/csvtk#40]
### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [ ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

**Comment by shenwei356** [comment]
https://github.com/shenwei356/csvtk/releases/tag/v0.13.0-dev2

**Comment by jmsegret** [comment]
Thanks
