### ISSUE TITLE
example split query

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#48]
Hi, I have an example operation that I think I will be able to do with csvtk but I am unsure how.
From a table that looks like this:

```
col1,col2,col3
100,2,ABC
101,2,DEF
```

I would like to have an operation on col2, so that foreach entry, two new entries are created where the value of col2 is divided by 2, and the value in col1 is suffixed with 'A' and 'B', e.g.:

```
col1,col2,col3
100A,1,ABC
100B,1,ABC
101A,1,DEF
101B,1,DEF
```

Any ideas how to construct that operation with csvtk?

**Comment by shenwei356** [comment]
It's nearly impossible. A script is a better choice

```
$ cat t.csv 
col1,col2,col3
100,2,ABC
101,2,DEF
102,3,GHI


$ cat t.csv | perl -ne 'if ($. == 1) { print } else { chomp; @data = split ",", $_; $s = ord("A"); $c1 = $data[0]; for (1..$data[1]){ $data[0] = $c1.chr($s++); $data[1] = 1; print join(",", @data), "\n";} }'
col1,col2,col3
100A,1,ABC
100B,1,ABC
101A,1,DEF
101B,1,DEF
102A,1,GHI
102B,1,GHI
102C,1,GHI
```

The perl one-liner:
