### ISSUE TITLE
ignore empty rows flag

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#50]
Hi,

I have a use case where I am using csvtk on a table from an .xlsx file where there could be rows at the bottom of the worksheet that are completely empty, e.g. where all the fields have empty cells. This is common if people manually edit the worksheet and just leave the empty rows in there rather than explicitly deleting them.

Could there be a flag in csvtk so that the empty rows are ignored in the csvtk operation?

There may be a workaround using csvtk filter or some other operation, but I couldn't find one.

E.g. in this example, all the values for the last two rows are empty

```
Col1,Col2,Col3
A,1,2
B,2,3
C,3,4
,,
,,
```

Currently when applying any operation, e.g. csvtk freq, it takes into account the empty rows:

```
csvtk freq -f 1 example_empty_rows.csv 
Col1,frequency
A,1
B,1
C,1
,2
```
It would be great to have an `--ignore-empty` e.g. `-e` flag that would filter out the rows where all fields are empty, then return the equivalent of the operation, e.g.:

```
csvtk freq --ignore-empty -f 1 example_empty_rows.csv 
Col1,frequency
A,1
B,1
C,1
```

**Comment by shenwei356** [comment]
[v0.15.0-dev3](https://github.com/shenwei356/csvtk/releases/tag/v0.15.0-dev3)

**Comment by avilella** [comment]
I tested it and got it working. Thanks!
