### ISSUE TITLE
csvtk cut remove multiple occurences

### ISSUE THREAD

**Issue by apeltzer** [shenwei356/csvtk#51]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

Hi, first thanks for this awesome tool! Works quite well with my data but I couldn't find a way to do the following with `featureCounts` output:

I have multiple files with this header (always the same header!):
```
Geneid	Chr	Start	End	Strand	Length	gene_name	blablabla.bam
```
If I join these together by Geneid, the table looks nice but "duplicated rows" exist (Chr, Start,End,Strand,Length,gene_name). 

I'd like to remove all columns Matching Chr,Start,End,Strand,Length (I assume with `-` as a prefix) but this only removes the first occurence of such a column. Can one specify to remove _all_ occurences of such a pattern, e.g. with an extra option `-g` ? 

Thanks, feel free to ask more questions if I'm being unclear!

**Comment by apeltzer** [comment]
Currently doing this here:

```
 csvtk join -t -f "Geneid" $input_files | csvtk cut -t -F -f "-6--2" | csvtk cut -t -f "-Start,-Chr,-End,-Length,-Strand,-gene_name" | sed 's/Aligned.sortedByCoord.out.markDups.bam//g' > merged_gene_counts.txt
``` 

That has the shortcoming that for more than two files there are multiple occurences of the columns Start,Chr,End,Length,Strand and gene_name in my file unfortunately.

**Comment by shenwei356** [comment]
Can you please paste several lines of few files😃

**Comment by apeltzer** [comment]
They all look like this for example:

```
 head -n 5 Test_multi.txt 
# Program:featureCounts v1.6.2; Command:"featureCounts" "-a" "../../../References/Human/GRCH38/annotation/Homo_sapiens.GRCh38.92.gtf" "-g" "gene_id" "-o" "Test_multi.txt" "-p" "-s" "0" "I18R036a15_01_S15Aligned.sortedByCoord.out.markDups.bam" "--extraAttributes" "gene_name,gene_biotype" 
Geneid	Chr	Start	End	Strand	Length	gene_name	gene_biotype	I18R036a15_01_S15Aligned.sortedByCoord.out.markDups.bam
ENSG00000223972	1;1;1;1;1;1;1;1;1	11869;12010;12179;12613;12613;12975;13221;13221;13453	12227;12057;12227;12721;12697;13052;13374;14409;13670	+;+;+;+;+;+;+;+;+	1735	DDX11L1	transcribed_unprocessed_pseudogene	0
ENSG00000227232	1;1;1;1;1;1;1;1;1;1;1	14404;15005;15796;16607;16858;17233;17606;17915;18268;24738;29534	14501;15038;15947;16765;17055;17368;17742;18061;18366;24891;29570	-;-;-;-;-;-;-;-;-;-;-	1351	WASH7P	unprocessed_pseudogene	0
ENSG00000278267	1	17369	17436	-	68	MIR6859-1	miRNA	3

```

**Comment by apeltzer** [comment]
Header is correctly parsed properly but when I join multiple of these files together, I end up having the columns Chr,Start,End,Strand,Length, gene_name more than once unfortunately.

**Comment by shenwei356** [comment]
how about joining by -f Genid,Chr,Start,End,Strand,Lenght,gene_name?

**Comment by apeltzer** [comment]
Works perfectly as expected :-) Thanks a lot for the help!
