### ISSUE TITLE
csvtk xlsx2csv file -a truncates worksheet name if too long

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#53]
### Prerequisites

- [x ] make sure you're are using the latest version by `csvtk version`
- [x ] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

I have an .xlsx file with long worksheet names, that get truncated when applying the -a as shown below:

csvtk xlsx2csv file.xlsx -a

The file.xlsx contains a worksheet like the one on the left, but csvtk returns a truncated name with the last character missing:

Import_XTP101_20181018102046_551 > Import_XTP101_20181018102046_55

* [x ] describe the problem
* [ ] provide a reproducible example

**Comment by avilella** [comment]
It seems to be Google Sheets related, see the test_csvtk.xlsx I created in Google Sheets:

https://docs.google.com/spreadsheets/d/1DGsrEKrxfQm8sRzfLyqu4z6Hx8eDdkVDiYlN3Rwve6A/edit?usp=sharing

And the result of downloading as .xlsx and using csvtk on it:
```
csvtk xlsx2csv test_csvtk.xlsx -a
index   sheet
1       Sheet1
2       Import_XTP101_20181018102046_55
3       Sheet5
4       Sheet6
```

**Comment by shenwei356** [comment]
Yes, and the 3rd and 4th sheet names are not right.

You can download as `.ods` file and then save as `.xlsx` using LibreOffice Calc / MS Excel. Then it works rightly.

**Comment by avilella** [comment]
I can confirm it works and can be used from the command-line:

loffice --headless --convert-to xlsx test_csvtk.ods
```
csvtk xlsx2csv test_csvtk.xlsx -a
index   sheet
1       Sheet1
2       Import_XTP101_20181018102046_551
3       Import_XTP101_20181018102046_551234567890
4       Import_XTP101_20181018102046_551111111111111111111111111111111222233333
```
