### ISSUE TITLE
[ERRO] parse error on line 2, column 104: extraneous or missing " in quoted-field

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#54]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

I am generating a .tsv file which contains single-quotes and double-quotes in the text, and when I pass it through csvtk pretty, I get this error:

```
[ERRO] parse error on line 2, column 105: extraneous or missing " in quoted-field
```
I tried getting rid of it by quoting the double-quotes as shown below, but the problem persists:

```
      my $this_record = "$this_created_at\t$this_created_time\t$this_user\t$this_message\t$this_comments";
      $this_record        =~ s/\"/\\\"/g;
```

Any ideas?

**Comment by avilella** [comment]
That solved the problem, thank you for the prompt reply!

**Comment by shenwei356** [comment]
You're welcome :smile:
