### ISSUE TITLE
mutate2 converts datetime expression to float

### ISSUE THREAD

**Issue by yubessy** [shenwei356/csvtk#55]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Datetime expression with single quotes (e.g. `'2018-10-31 01:23:45'`) will be converted to float when using `csvtk mutate2` in order to append a new column to original file.
Is this an expected behavior or not?

```
$ csvtk version
csvtk v0.15.0

Checking new version...
You are using the latest version of csvtk

$ cat source.csv
aaa,bbb
1,x
2,y
3,z

$ cat source.csv | csvtk mutate2 -n ts -e "'2018-10-31 01:23:45'"
aaa,bbb,ts
1,x,1.540916625e+09
2,y,1.540916625e+09
3,z,1.540916625e+09

$ cat source.csv | csvtk mutate2 -s -n ts -e "'2018-10-31 01:23:45'"
aaa,bbb,ts
1,x,1.540916625e+09
2,y,1.540916625e+09
3,z,1.540916625e+09
```

**Comment by shenwei356** [comment]
Well, the [govaluate](https://github.com/Knetic/govaluate/blob/0580e9b47a69125afa0e4ebd1cf93c49eb5a43ec/parsing.go#L127) package parses any date like format to UTC seconds. No option to avoid this.

Here's are two workaround solutions:

```
# make it unlike data format
$cat source.csv | csvtk mutate2 -n ts -e "'2018-10-31 01:23:45_'" | csvtk replace -f ts -p _ 
aaa,bbb,ts
1,x,2018-10-31 01:23:45
2,y,2018-10-31 01:23:45
3,z,2018-10-31 01:23:45
```

```
$ cat source.csv | csvtk mutate -n ts | csvtk replace -f ts -p .+ -r '2018-10-31 01:23:45'
aaa,bbb,ts
1,x,2018-10-31 01:23:45
2,y,2018-10-31 01:23:45
3,z,2018-10-31 01:23:45
```

**Comment by yubessy** [comment]
I see. Thanks for workarounds!
