### ISSUE TITLE
regexp for mutate

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#57]
### Prerequisites

- [x] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [x] describe the problem

I am trying to perform a regexp replace with csvtk mutate but not obtaining the right result.

* [x] provide a reproducible example

For an input file with a Position field, I want to get rid of the preceding zeros between the letter and number, e.g. from A01 to A1, but preserving A10 to A10:

cat file.csv ¦ csvtk mutate -f Position -n 'Elution Tube'  -p "^(.)0(.+)$"

```
Box,BARCODE,Position,Elution Tube
SA00719315,FD10055219,A01,A
SA00719315,FD10055227,A02,A
SA00719315,FD10055235,A03,A
SA00719315,FD10055243,A04,A
SA00719315,FD10055251,A05,A
SA00719315,FD10055259,A06,A
SA00719315,FD10055267,A07,A
SA00719315,FD10055275,A08,A
SA00719315,FD10055283,A09,A
SA00719315,FD10055291,A10,A10
SA00719315,FD10055299,A11,A11
SA00719315,FD10055307,A12,A12
SA00719315,FD10055220,B01,B
SA00719315,FD10055228,B02,B
SA00719315,FD10055236,B03,B
```
Any ideas? Thanks in advance

**Comment by shenwei356** [comment]
cat file.csv ¦ csvtk mutate -f Position -n 'Elution Tube' | csvtk replace -f 'Elution Tube' -p '^(.)0(.+)$' -r '$1$2'

**Comment by avilella** [comment]
Very many thanks
