### ISSUE TITLE
group / sum values in column from csvtk freq

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#59]
This is I believe a feature request although there may already be a way of doing this. I have a table with a column that's supposed to be numerical, e.g. 1, 2, 1.5, etc. The entries in the table are sometimes 'NA' or 'N/A', but still I would like to group by certain column(s) and apply an operation on this column (sum).

If all entries were numerical, I would currently use https://github.com/agordon/datamash for this. But if there is a way of doing it with csvtk and a way that takes care of NAs, I would love to be able to do this in csvtk.

Example:
```
f1,f2,f3,f4
foo,bar,xyz,1
foo,bar2,xyz2,1.5
bar,xyz,abc,NA
bar,xyz2,abc2,1
bar,xyz3,abc3,1
```

**Comment by shenwei356** [comment]
We may rewrite `csvtk stats2`:

```
csvtk stats2 -g f1 -f count:f4 -f sum:f4 --ignore-non-digits
```

or better:

```
csvtk stats2 -g f1,f2 -f f4:sum,count,mean --ignore-non-digits
```

**Comment by avilella** [comment]
That sounds great.

**Comment by shenwei356** [comment]
Try this:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2677078/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2677079/csvtk_linux_amd64.tar.gz)

Available operations:

	count, min, max, sum
	mean, stdev, variance
	entropy, prod
        q1, q2, q3, median # not implemented yet

Too complex operations are not taken into consideration.

Examples:

    $ cat digitals2.csv 
    f1,f2,f3,f4
    foo,bar,xyz,1
    foo,bar2,xyz,1.5
    foo,bar2,xyz,3
    foo,bar,xyz,5
    foo,bar2,xyz,N/A
    bar,xyz,abc,NA
    bar,xyz,abc2,1
    bar,xyz,abc,2
    bar,xyz,abc,1
    bar,xyz,abc,3
    bar,xyz2,abc3,2
    bar,xyz2,abc3,2


    $ cat digitals2.csv | csvtk stats -f f4:sum
    [ERRO] column 4 has non-digital data: N/A, you can use flag -i/--ignore-non-digits to skip these data

    $ cat digitals2.csv | csvtk stats -i -f f4:sum 
    f4:sum
    21.50

    $ cat digitals2.csv | csvtk stats -i -f f4:sum -g f1
    f1      f4:sum
    bar     11.00
    foo     10.50

    $ cat digitals2.csv | csvtk stats -i -f f4:sum -g f1,f2
    f1      f2      f4:sum
    bar     xyz     7.00
    bar     xyz2    4.00
    foo     bar     6.00
    foo     bar2    4.50

    $ cat digitals2.csv | csvtk stats -i -g f1 -f f4:count,f4:sum,f4:mean | csvtk pretty -t
    f1    f4:count   f4:sum   f4:mean
    bar   6.00       11.00    1.83
    foo   4.00       10.50    2.62

    # no header line

    $ cat digitals2.csv | sed 1d | csvtk stats -H -i -g 1 -f 4:count,4:sum,4:mean | csvtk pretty -t
    bar   6.00   11.00   1.83
    foo   4.00   10.50   2.62

    # you can't mix use digital fields and column names

    $ cat digitals2.csv | sed 1d | csvtk stats -i -g f1 -f 4:count
    [ERRO] fail to parse digital field: f1, you may mix use digital fields and column names

**Comment by avilella** [comment]
I have tested it and it works as expected. Thanks for implementing it.

The output delimiter is tab by default. Can it be comma-separated? I tried
`-D ','` but still got tab output. Small detail, let me know what you think.

**Comment by avilella** [comment]
The ignore-non-digits is very useful, and already makes csvtk more feature
rich than datamash. Greatly appreciated

**Comment by shenwei356** [comment]
Dear Albert, please try again and test it, if no bug exists I'll release a new version.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2678565/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2678566/csvtk_linux_amd64.tar.gz)

Usage:

```
$ csvtk stats -h
summary statistics of selected digital fields (groupby group fields)

Attention:

  1. Do not mix use digital fields and column names.

Available operations:
 
  # provided by github.com/gonum/stat and github.com/gonum/floats
  count, min, max, sum,
  mean, stdev, variance, median, q1, q2, q3,
  entropy (Shannon entropy), 
  prod (product of the elements)

Usage:
  csvtk stats [flags]

Aliases:
  stats, stat

Flags:
  -n, --decimal-width int   limit floats to N decimal points (default 2)
  -f, --fields strings      operations on these fields. e.g -f 1:count,1:sum or -f colA:mean. available operations: count, entropy, max, mean, median, min, prod, q1, q2, q3, stdev, sum, variance
  -g, --groups string       group via fields. e.g -f 1,2 or -f columnA,columnB
  -h, --help                help for stats
  -i, --ignore-non-digits   ignore non-digital values like "NA" or "N/A"
```

**Comment by avilella** [comment]
Hi again,

I have several pieces of infrastructure that still rely on the
old-behaviour `csvtk stats` but I would benefit very much from the new data
mash behaviour.

Can I propose that the new features are added to a `csvtk mash` mode and
the old `csvtk stats` is kept untouched?

Thanks very much, this is making a real difference to our daily work.

**Comment by shenwei356** [comment]
Fine,  let's  keep the old 'csvtk stats' with aliases of 'dim' and 'size', and still use 'csvtk stats2' for these new features.

**Comment by avilella** [comment]
Great, I have not been using stats2, so none of my code will need changing
if the new features fall into the new stats2 behaviour.

**Comment by shenwei356** [comment]
Well, I'll name it 'csvtk summary'.
There are too may 'xxx2's, mutate2, filter2, rename2, how often do you use these commands.

Which commands are you using? Can you rank them by using frequency?

**Comment by avilella** [comment]
In my bash history (there may be a few mistyped ones), column number 1 is
number of occurences:

      2 csvtk header
      2 csvtk stat2
      3 csvtk tranpose
      4 csvtk version
      6 csvtk xslx2csv
      7 csvtk collapse
      7 csvtk csv2tab
      7 csvtk mutate
      8 csvtk gather
     14 csvtk replace
     14 csvtk uniq
     51 csvtk plot
     53 csvtk rename
     64 csvtk stats2
     77 csvtk inter
    102 csvtk mutate2
    157 csvtk sort
    188 csvtk stats
    208 csvtk concat
    267 csvtk grep
    303 csvtk filter
    345 csvtk headers
    486 csvtk transpose
    640 csvtk pretty
    700 csvtk freq
    756 csvtk join
   1066 csvtk xlsx2csv
   1075 csvtk cut

I my code:

      1 csvtk mutate2
      1 csvtk rename
      1 csvtk replace
      1 csvtk stats2
      4 csvtk freq
      5 csvtk concat
      5 csvtk join
      5 csvtk transpose
      6 csvtk sort
      8 csvtk filter
      8 csvtk stats
     10 csvtk headers
     28 csvtk cut
     52 csvtk xlsx2csv

**Comment by shenwei356** [comment]
Alright, final change:

- old `csvtk stats` renamed to `csvtk dim` with aliases of `size`, `stats`, and `stat`.
- old `csvtk stats2 removed.
- newly added `csvtk summary` .

Please have a try:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2680800/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2680801/csvtk_linux_amd64.tar.gz)

**Comment by shenwei356** [comment]
See [v0.16.0](https://github.com/shenwei356/csvtk/releases/tag/v0.16.0).
