### ISSUE TITLE
feature request: toascii

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#60]
This may be implemented in a standalone UNIX tool, but it would be great if it could be part of csvtk:

Would it be possible to have an `csvtk toascii` or similarly named command that takes an input and converts any non-ASCII characters to their ASCII closest equivalent?

Thanks in advance,

**Comment by shenwei356** [comment]
Hi Albert, I believe this function is out of scope of csvtk. 

Although, there are some `iconv`-like package. Do you want convert single characters in some columns of whole data stream?

**Comment by avilella** [comment]
I want to convert, by passing it through the UNIX pipe, any non-ASCII
characters to their ASCII equivelent, then pass it to csvtk for further
processing. What do you recommend? Thanks in advance.

**Comment by shenwei356** [comment]
try iconv, it seems what you need.
