### ISSUE TITLE
add header command

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#62]
Would it be possible to have an add header(s) command to csvtk, if there isn't an easy way to do it yet?

E.g.
```
cat file.csv
1
2
3
4

csvtk add-header -f 1:myheader file.csv
myheader
1
2
3
4
```

Thanks in advance for considering. I wanted a more elegant way than the following for 1-column files:

```
{ echo myheader ; cat file.csv ; }

**Comment by shenwei356** [comment]
Ok, I need this too

**Comment by shenwei356** [comment]
Added:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2775541/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2775542/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/2775543/csvtk_windows_amd64.exe.tar.gz)

Examples:

```
$ seq 3 | csvtk mutate -H | csvtk add-header -n a,b
a,b
1,1
2,2
3,3

$ seq 3 | csvtk mutate -H -t | csvtk add-header -t -n a,b
a       b
1       1
2       2
3       3
```

**Comment by shenwei356** [comment]
`csvtk del-header` is added too, you can also use  `sed 1d` in *nix.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2775569/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2775570/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/2775571/csvtk_windows_amd64.exe.tar.gz)

```
$ seq 3 | csvtk mutate -H | csvtk add-header -n a,b | csvtk del-header 
1,1
2,2
3,3
```
