### ISSUE TITLE
How to handle numeric column title in csvtk cut argument

### ISSUE THREAD

**Issue by xiaoyonf** [shenwei356/csvtk#63]
Hi, I need to extract a subset of data from a big csv file using specific column title, which are numerics. For example, I have two columns with titles as 910930 and 909751, and I try to use csvtk cut command as: 

    csvtk cut -f 910930,909751 input.csv > output.csv

but i got the error: 

    [ERRO] field (910930) out of range (1019) in file:

How do I handle this problem? Thanks a lot!

 -Xiaoyong

**Comment by shenwei356** [comment]
add some letters to all column names using https://bioinf.shenwei.me/csvtk/usage/#rename2

    csvtk rename2 -F -f '*' -p ^ -r c

then

    csvtk cut -f c1234,c2345
