### ISSUE TITLE
freature request: implement grouping operations

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#64]
The last set of features in datamash that are now missing in the superior csvtk are the grouping operations below:
```
Textual/Numeric Grouping operations:
  count, first, last, rand, unique, collapse, countunique
```

Example below: datamash supposes tabular separator, so it creates extra commas in the unique grouping command below. I presume a solution is to specify the separator for the grouping:

Something like:
```
csvtk summary -g 1 2:unique --group-separator ':'
```

Example from datamash on an input .csv:

```
avilella@albertLX1u16:/media/sf_Downloads$ csvtk cut -f sample_id,lane CEGX_Run701p712p703.lanes.csv | head
sample_id,lane
CEG99_701_74PC,3
CEG99_701_74PC,4
CEG99_701_01IC,1
CEG99_701_01IC,2
CEG99_701_29IC,1
CEG99_701_29IC,2
CEG99_701_92PC,3
CEG99_701_92PC,4
CEG99_701_50IC,1
avilella@albertLX1u16:/media/sf_Downloads$ csvtk cut -f sample_id,lane CEGX_Run701p712p703.lanes.csv | datamash -t ',' -g 1 unique 2 | head
sample_id,lane
CEG99_701_74PC,3,4
CEG99_701_01IC,1,2
CEG99_701_29IC,1,2
CEG99_701_92PC,3,4
CEG99_701_50IC,1,2
CEG99_701_54PC,3,4
CEG99_701_11IC,1,2
CEG99_701_41PC,3,4
CEG99_701_28IC,1,2
```

**Comment by shenwei356** [comment]
OK, I'll add theses operations.

For you example, the `collapse` command can do this:

```
$ csvtk collapse t.csv -f sample_id -v lane -s ,
sample_id,lane
CEG99_701_74PC,"3,4"
CEG99_701_01IC,"1,2"
CEG99_701_29IC,"1,2"
CEG99_701_92PC,"3,4"
CEG99_701_50IC,1
```

**Comment by avilella** [comment]
Brilliant! Thanks again for your support in bringing in these feature
requests and turning csvtk in such a great tool!

**Comment by shenwei356** [comment]
@avilella , it's ready for testing:

- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2855198/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/2855197/csvtk_darwin_amd64.tar.gz)


1. textual/numeric operations

        $  cat testdata/digitals2.csv \
            | csvtk summary -i -g f1 -f f2:count,f2:first,f2:last,f2:rand,f2:collapse,f2:uniq,f2:countunique \
            | csvtk pretty
        f1    f2:count   f2:first   f2:last   f2:rand   f2:collapse                           f2:uniq     f2:countunique
        bar   7          xyz        xyz2      xyz2      xyz; xyz; xyz; xyz; xyz; xyz2; xyz2   xyz2; xyz   2
        foo   5          bar        bar2      bar2      bar; bar2; bar2; bar; bar2            bar; bar2   2

1. mixed operations

        $  cat testdata/digitals2.csv \
            | csvtk summary -i -g f1 -f f4:collapse,f4:max \
            | csvtk pretty
        f1    f4:collapse            f4:max
        bar   NA; 1; 2; 1; 3; 2; 2   3.00
        foo   1; 1.5; 3; 5; N/A      5.00
