### ISSUE TITLE
batching using int() or similar

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#65]
This is a feature request for an operation (it may already exist as a different solution) to be able to do batching obtaining the integer of a mutate2 (or similar) operation. E.g. my aim is to get to something like:
```
seq 1 100 | csvtk add-header -n wells | csvtk mutate2 -n batch -e 'int(($wells/96)+1)' | csvtk freq -f wells
batch,frequency
1,96
2,4
```
I wonder if there is such operator that will give me the integer shown as `int()` above or equivalent.

Thanks in advance

**Comment by shenwei356** [comment]
The artithmetic/string expression is supported by [https://github.com/Knetic/govaluate](https://github.com/Knetic/govaluate#what-operators-and-types-does-this-support). `int()` is not supported.

```
Supported operators and types:

  Modifiers: + - / * & | ^ ** % >> <<
  Comparators: > >= < <= == != =~ !~
  Logical ops: || &&
  Numeric constants, as 64-bit floating point (12345.678)
  String constants (single quotes: 'foobar')
  Date constants (single quotes)
  Boolean constants: true false
  Parenthesis to control order of evaluation ( )
  Arrays (anything separated by , within parenthesis: (1, 2, 'foo'))
  Prefixes: ! - ~
  Ternary conditional: ? :
  Null coalescence: ??
``
