### ISSUE TITLE
Logical error of  replace

### ISSUE THREAD

**Issue by flystar233** [shenwei356/csvtk#67]
the first error：
```
$ cat data.tsv
name    id
A       ID001
B       ID002
C       ID004

$ cat alias.tsv
001     Tom
002     Bob
003     Jim

$ csvtk replace -t -f 2 -p "ID(.+)" -r "N: {nr}, alias: {kv}" -k alias.tsv data.tsv
name    id
A       N: 1, alias: Tom
B       N: 2, alias: Bob
C       N: 3, alias: 
```
When there is no key corresponding to the data file in the key-value pair file, the data in the data file should be given instead of that in the key-value pair. Therefore, the final output should be N:4 instead of N: 3

the second error：
```
$ cat data.tsv
name    id
A       ID001
B       ID002
C       ID004

$ cat alias.tsv
001     Tom
002     Bob
003     Jim
004    july
$ csvtk replace -t -f 2 -p "ID(.+)" -r "N: {nr}, alias: {kv}" -k alias.tsv data.tsv
name    id
A       N: 1, alias: tom
B       N: 2, alias: bob
C       N: 3, alias: july
```
This is a fatal mistake~~

**Comment by shenwei356** [comment]
> When there is no key corresponding to the data file in the key-value pair file, the data in the data file should be given instead of that in the key-value pair. 

Use:

      -K, --keep-key               keep the key as value when no value found for the key


> Therefore, the final output should be N:4 instead of N: 3

It's nothing to do with key-value pairs.

    {nr}    Record number, starting from 1

Second "error" looks right.

**Comment by flystar233** [comment]
I misunderstood the meaning of {nr}, thank you for your answer.
