### ISSUE TITLE
pipelining

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#68]
I'm normalizing some tables, so I need to copy some cols selectively, then replace header, uniq and sort. I can do it by pipelining in unix: 
```sh
csvtk cut ... input | csvtk replace ... | csvtk uniq ... | csvtk sort ... > output
```

But the file is a few gigabytes, and all these intermediate (temp) files between pipeline steps slow things down.

It would be great if the tool supported internal pipelining. The syntax needs to be worked out, but maybe something like
```sh
csvtk cut ... replace ... uniq ... sort ... input > output
```

BTW, thanks for this excellent tool!

**Comment by shenwei356** [comment]
Are there intermediate files created between pipes?

Due to the original design, it's quite hard and completed to support internal pipelining. But it's really a good advice.

**Comment by VladimirAlexiev** [comment]
Maybe there aren't: https://unix.stackexchange.com/questions/165160/how-does-bash-pipe-large-amounts-of-data. Talks of pipeline buffers that transfer data from one program to the next.
But I guess that depends on the OS. Eg I'm on Windows and use Cygwin, and I don't know whether it does such buffering.
