### ISSUE TITLE
fix documentation highlighting

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#69]
https://bioinf.shenwei.me/csvtk/usage/ sample code and output includes spurious highlighting, which is quite distracting.

Please select an appropriate language (`sh` for the command, `text` for the output). Or just turn off all highlighting

**Comment by shenwei356** [comment]
Usage of sub-commands are fixed, but code snippets are not because indented code blocks do not support   specifying the language.
