### ISSUE TITLE
Option to continue after error

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#72]
I'm running cut on a very large file (10M rows).
 
> [ERRO] record on line 8021228: wrong number of fields 

It would be very useful if csvtk could skip the bad row and continue

**Comment by shenwei356** [comment]
Well, this can be added.

- Err can be captured here: https://golang.org/src/encoding/csv/reader.go?s=1688:1915#L88
- To add here: https://github.com/shenwei356/csvtk/blob/master/csvtk/cmd/csv.go#L48

**Comment by shenwei356** [comment]
A flag `--ignore-illegal-row` added:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3169862/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3169863/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/3169864/csvtk_windows_amd64.exe.tar.gz)

Examples:

```
$ cat t.csv 
1,1
,
3,3
4
5,5
6,6,6
7,7
 
$ cat t.csv -A
1,1$
,$
3,3$
4$
5,5$
6,6,6$
7,7$
 $

$ csvtk pretty t.csv -I -E
[WARN] 1 empty rows ignored
[WARN] 3 illegal rows ignored
1   1
3   3
5   5
7   7
```
