### ISSUE TITLE
allow any quotes in tab-separated file

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#73]
I thought option `-l` (loose quotes) would allow me to have any quotes in tab-separated file that doesn't have any tabs inside the fields. Eg one of the fields (some address) looks like this:
`"Street" # 209, 4th cross, 2nd main`

But that option just changes the error message (first is without, second is with):
```
[ERRO] parse error on line 3, column 50: extraneous or missing " in quoted-field
[ERRO] record on line 3: wrong number of fields
```

**Comment by shenwei356** [comment]
[std lib](https://golang.org/pkg/encoding/csv/)  is used for CSV parsing, which supports the format described in RFC 4180.

The legal format of the Eg is:

```
$ cat t.csv
id,addr
1,"""Street"" # 209, 4th cross, 2nd main"

$ csvtk pretty t.csv
id   addr
1    "Street" # 209, 4th cross, 2nd main
```
