### ISSUE TITLE
option to allow any quotes in tab-separated file

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#74]
I thought option `-l` (loose quotes) would allow me to have any quotes in tab-separated file that doesn't have any tabs inside the fields. Eg one of the fields (some address) looks like this:
`"Street" # 209, 4th cross, 2nd main`

But that option just changes the error message (first is without, second is with):
```
[ERRO] parse error on line 3, column 50: extraneous or missing " in quoted-field
[ERRO] record on line 3: wrong number of fields
```

**Comment by VladimirAlexiev** [comment]
I had a similar problem with a tool that converts TSV to RDF (`tarql`) that uses the OpenCSV java library for parsing. https://github.com/tarql/tarql/issues/50#issuecomment-268845091

However, that library gets confused only when there is an **odd** number of quotes, whereas csvtk also has a problem with even number of quotes, if one is at start of the field but the other is not.

**Comment by shenwei356** [comment]
[std lib](https://golang.org/pkg/encoding/csv/)  is used for CSV parsing, which supports the format described in RFC 4180.

The legal format of the Eg is:

```
$ cat t.csv
id,addr
1,"""Street"" # 209, 4th cross, 2nd main"

$ csvtk pretty t.csv
id   addr
1    "Street" # 209, 4th cross, 2nd main
```

**Comment by VladimirAlexiev** [comment]
There are standards, and then there are real-world files that always break the standard :-)

I could preprocess the file as indicated... But then what exactly is the `-l` option for?

**Comment by shenwei356** [comment]
It's a port to option `LazyQuotes` in the [std lib CSV reader](https://golang.org/pkg/encoding/csv/#Reader)

```
type Reader struct {
        // If LazyQuotes is true, a quote may appear in an unquoted field and a
        // non-doubled quote may appear in a quoted field.
        LazyQuotes bool

```

**Comment by dariober** [comment]
I'm looking into options to replace Unix's `sort`, `awk`, etc. with header-aware tools. csvtk and csvkit look pretty good but the issue with quotes is kind of a killer... In bioinformatics there are lots of tab-separated files where quotes have no special meaning (e.g. GTF/GFF, user generated files in general). Is there any workaround or toolkit that is less stringent about CSV format?

**Comment by shenwei356** [comment]
That needs a new CSV/TSV parser.

Try https://github.com/BurntSushi/xsv , https://github.com/johnkerl/miller ?
