### ISSUE TITLE
xlsx2csv Ignores Some Global Flags

### ISSUE THREAD

**Issue by njgray** [shenwei356/csvtk#78]
### Prerequisites

- [X] make sure you're are using the latest version by `csvtk version`
```
$ csvtk version
csvtk v0.18.0

Checking new version...
You are using the latest version of csvtk
```
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)
[Global flags](https://bioinf.shenwei.me/csvtk/usage/#csvtk)
[Help for xslx2csv](https://bioinf.shenwei.me/csvtk/usage/#xlsx2csv)

### Describe your issue

When using the xlsx2csv command, the global flags `-T`, `-D` seem to be ignored or incompatible. Those are the only two flags I tried to use, so it may apply to more (all?) global flags.

#### Example:
[testSpreadsheet.xlsx](https://github.com/shenwei356/csvtk/files/3204175/testSpreadsheet.xlsx)

Using the attached test spreadsheet and running `csvtk xlsx2csv testSpreadsheet.xlsx -D "|"` produces:
```
ColA,ColB,ColC,ColD
A1,B1,C1,D1
A2,B2,C2,D2
A3,B3,C3,D3
A4,B4,C4,D4
A5,B5,C5,D5
```

However running `csvtk xlsx2csv testSpreadsheet.xlsx | csvtk cut -F -f "*" -D "|"` gives the expected result:
```
ColA|ColB|ColC|ColD
A1|B1|C1|D1
A2|B2|C2|D2
A3|B3|C3|D3
A4|B4|C4|D4
A5|B5|C5|D5
```

**Comment by shenwei356** [comment]
You're right, it ignores nearly all global flags. I'll fix this.

**Comment by shenwei356** [comment]
It reacts to global flags `-t`, `-T`, `-D` and `-E` now.

Try the pre-release:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3215801/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3215802/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/3215803/csvtk_windows_amd64.exe.tar.gz)
