### ISSUE TITLE
A doubt about csvtk sort

### ISSUE THREAD

**Issue by flystar233** [shenwei356/csvtk#79]
I am a bioinformatics worker and often deal with some genotype files like this :
```
chr10   111     A T T
chr10   222     A T T
chr11   111     A T T
chr1    122     A T T
chr20   111     A T T
chr20   222     A T T
chr2    111     A T T
```
The frist column was out-of-order when `cat` all chromosome genotype files.  So I used
```
csvtk -H -t  sort -k 1:N  text.txt
```
The result is :
```
chr1    122     A T T
chr2    111     A T T
chr10   111     A T T
chr10   222     A T T
chr11   111     A T T
chr20   222     A T T
chr20   111     A T T
```
OK~,The first column was ordered correctly，but the chr20 snp site of second column is out-of-order，even if I used `csvtk -H -t  sort -k 1:N -k 2:n text.txt`, The result was not changed:
```
chr1    122     A T T
chr2    111     A T T
chr10   111     A T T
chr10   222     A T T
chr11   111     A T T
chr20   222     A T T
chr20   111     A T T
```
I don't know what happened inside the program.

**Comment by shenwei356** [comment]
Sorry, it's a little bug and fixed now, you can try the pre-release here:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3212756/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3212757/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/3212758/csvtk_windows_amd64.exe.tar.gz)

**Comment by flystar233** [comment]
Thank you for your contribution~, it works correctly.
