### ISSUE TITLE
Feature request : Ability to do CSV SET difference (EXCEPT or MINUS )

### ISSUE THREAD

**Issue by tsundara** [shenwei356/csvtk#80]
Hi ShenWei
This is a suggestion to create a new subcommand to perform SET difference.
At my work, I had to write a bash script to load 2 csv files into sqlite, find the set difference using "except" operator, insert the result to a new table and then export the table. 

It would be super convenient to have this feature in csvtk.

**Comment by shenwei356** [comment]
Try [csvtk grep -v](http://bioinf.shenwei.me/csvtk/usage/#grep).
