### ISSUE TITLE
xlsx to csv保留公式？

### ISSUE THREAD

**Issue by jtliaw** [shenwei356/csvtk#81]
抱歉！想请问大神！ csvtk能将xlsx或者ods转csv并且保留公式（formula）吗？ 在您的使用手册上没有看到能调整的命令！
--

### Prerequisites

- [ ] make sure you're are using the latest version by `csvtk version`
- [x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

**Comment by jtliaw** [comment]
抱歉！想请问大神！
csvtk能将xlsx或者ods转csv并且保留公式（formula）吗？
在您的使用手册上没有看到能调整的命令！

**Comment by shenwei356** [comment]
什么场景？csv格式里面的公式有何意义？

**Comment by jtliaw** [comment]
感谢您的回答！
是这样的！我使用linux shell制作了一个扣除存货的软件，将手机扫描的货物通过云端到linux，并且扣除存货。但是linux shell只能写入到csv格式！
就目前我所能做到的是：
从csv转到ods或者xls就能保存formula！但倒反回来却不行！
有formula的csv使用libreoffice编制后再保存为csv，formula就会消失了！
必须保存为ods或者xls，然后再打开ods或者xls另存为csv方可，非常麻烦！

**Comment by shenwei356** [comment]
应该可以的，excel库支持获取cell formula操作 https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetCellFormula ，只是效率会比较低下，空了实现。

**Comment by jtliaw** [comment]
那么您的csvtk能实现吗？

**Comment by shenwei356** [comment]
> 空了实现。
> I'll implement it when I'm free.

**Comment by eilandnl** [comment]
what about password protected files

**Comment by hmyh1202** [comment]
> 
> 
> what about password protected files

special question !
