### ISSUE TITLE
header 带 #符号貌似有问题？

### ISSUE THREAD

**Issue by flying-polarbear** [shenwei356/csvtk#85]
shenwei您好!
用的最新版：
`csvtk verisions`
```
csvtk v0.18.2
Checking new version...
You are using the latest version of csvtk
```
本人有个tsv文件，就简单的想看下header，但是header是#号开头的，比如#char pos...
按照help提示，用命令`csvtk headers -t -C '#' my_file.tab`
但是得到的是第二行的文本数据。

于是测试以一个数据：
header_test:
---
1,2,3,4,5,66
a,a,a,a,a,aa
---
`csvtk headers header_test`
结果无误，把header加个#号
---
#1,2,3,4,5,66
a,a,a,a,a,aa
---
`csvtk headers -C '#' header_test`
结果是第二行

不知道是我理解错了还是这是不正常的结果？？
谢谢！

**Comment by shenwei356** [comment]
https://bioinf.shenwei.me/csvtk/usage/#before-use

> By default, lines starting with # will be ignored, if the header row starts with #, please assign flag -C another rare symbol, e.g. '$'.

Should be:

    csvtk headers -C '$' header_test
