### ISSUE TITLE
config的功能增加

### ISSUE THREAD

**Issue by flying-polarbear** [shenwei356/csvtk#86]
shenwei您好！

提出一个新的功能看能不能加上。
比如运行`csvtk cut -f f1,f2,f3  file`之类的命令时，假如需要的列特别多，写在命令里太麻烦了，可以用config file的形式写在一个文件里：`csvtk cut -f config  file`的形式调用-f选项。

谢谢！

**Comment by shenwei356** [comment]
那得有多多？太多了你就扔文件里面，用paste读取，弄成一行

    csvtk cut -f $(paste -s -d , columns_file) file

还可以用“负选择”，去掉不需要的列。

    # remove column f4, f5
    csvtk cut -f -f4,-f5 file

**Comment by flying-polarbear** [comment]
有大几百上千列，需要和不需要的都很多，一开始没注意使用嵌套shell的方法，问题解决了，谢谢！
