### ISSUE TITLE
csvtk cut according to names from file

### ISSUE THREAD

**Issue by hufanglq** [shenwei356/csvtk#89]
Thank you for creating such excellent tools! But it's not very convenient when I have to select hundreds of columns. Can csvtk cut use the -P parameters to read colnames from file just csvtk grep? This is similar to https://www.biostars.org/p/248049/

**Comment by shenwei356** [comment]
csvtk cut -f $(paste -s -d , columns.txt) data.csv

**Comment by hufanglq** [comment]
Thanks! This works well.
