### ISSUE TITLE
 submodule doc/site does not exist

### ISSUE THREAD

**Issue by jondegenhardt** [shenwei356/csvtk#9]
Tried to clone the repo, got a failure:
```
$ git clone --recursive https://github.com/shenwei356/csvtk.git
...
fatal: No url found for submodule path 'doc/site' in .gitmodules
```
In the github UI it shows up as a non-clickable link. Commands like:
```
$ go get -u github.com/shenwei356/csvtk/csvtk
```
fail also showing the same issue.

**Comment by shenwei356** [comment]
This works fine:

    git clone  https://github.com/shenwei356/csvtk.git

**Comment by shenwei356** [comment]
It's fixed now, by adding the "doc/site" to `.gitignore`

**Comment by jondegenhardt** [comment]
Thanks for the quick fix. Still errors out though. Do you have to 'git rm doc/site' perhaps?

**Comment by shenwei356** [comment]
Thank your advise, it works now..

**Comment by jondegenhardt** [comment]
Wow, very quick response, seems to work now. Thanks!
