### ISSUE TITLE
Zero quartiles for single-observation cases

### ISSUE THREAD

**Issue by vmikk** [shenwei356/csvtk#90]
Hello!

Currently, when there is only one observation in data, `csvtk summary` returns quartiles (Q1 & Q3) = 0:
```
# Create dummy file (a little bit slow)
cd /tmp
echo "Col1,Col2" > dummy.csv
echo "a,100" >> dummy.csv
echo "b,200" >> dummy.csv
echo "c,30" >> dummy.csv
echo "c,40" >> dummy.csv
echo "c,50" >> dummy.csv

csvtk summary -f Col2:median,Col2:q1,Col2:q3,Col2:variance,Col2:countn -g Col1 dummy.csv | csvtk pretty
```

Which results in:
```
Col1   Col2:median   Col2:q1   Col2:q3   Col2:variance   Col2:countn
a      100.00        0.00      0.00      NaN             1
b      200.00        0.00      0.00      NaN             1
c      40.00         30.00     50.00     100.00          3
```

As you may see, q1 & q3 = 0 for single-observation cases (a and b), which is not correct.
In such cases other programs (e.g., R, datamash, numpy) return the observed value:
```
Rscript -e 'quantile(x = 100, probs = c(0.25, 0.75))'
echo "100" | datamash q1 1 q3 1
echo "100" | python3 -c "import fileinput as FI,numpy as np; i = [int(l) for l in FI.input()]; print('q1:', np.percentile(i, 25), ' q3: ', np.percentile(i, 75))"
# all of the above commands should return Q1=100 & Q3=100
```

- csvtk - v.0.19.0 (installed via conda)

With best regards,
Vladimir

**Comment by shenwei356** [comment]
fixed.

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3690577/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3690578/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/3690579/csvtk_windows_amd64.exe.tar.gz)
