### ISSUE TITLE
converting pairwise values into a matrix or semi-matrix

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#91]
There may already be a solution to this with a combination of `summary` or `gather` or `collapse` but here is a feature request I find myself wanting to do every once in a while:

https://stackoverflow.com/questions/22492767/converting-pairwise-distances-into-a-distance-matrix-in-r

Take a list of pairwise distances and convert into a matrix:
```
A1  A1  0.90
A1  B1  0.85
A1  C1  0.45
A1  D1  0.96
B1  B1  0.90
B1  C1  0.85
B1  D1  0.56
C1  C1  0.55
C1  D1  0.45
D1  D1  0.90
```

E.g. below:

```
       A1      B1      C1      D1
A1    0.90    0.85    0.45    0.96
B1            0.90    0.85    0.56
C1                    0.55    0.45
D1                            0.90
```

**Comment by avilella** [comment]
This is currently what a similar tool to `csvtk` does for this contingency table generation:

` cat data.tsv | datamash crosstab 2,1 unique 3`

**Comment by shenwei356** [comment]
I think this case is too special, I mean, maybe there are very few people needing this. And since `datamash` provides this function, there's no need to reinvent this wheel right now.

**Comment by cwarden** [comment]
I don't think the use case is too unusual.  tidyr provides `spread` as the inverse of `gather` (now `pivot_longer` and `pivot_wider`).  The [pivot documentation](https://tidyr.tidyverse.org/articles/pivot.html) provides example use cases.

**Comment by avilella** [comment]
I had use cases for this as well, currently using datamash instead, but it
would be nice to have it in csvtk for easier portability.

**Comment by shenwei356** [comment]
Implemented:

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12319920/csvtk_darwin_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/12319922/csvtk_darwin_arm64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/12319925/csvtk_linux_amd64.tar.gz)

Your data

    $ csvtk spread -Ht -k 2 -v 3 data.tsv \
        |  csvtk pretty -t -S bold

    ┏━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┓
    ┃    ┃ A1   ┃ B1   ┃ C1   ┃ D1   ┃
    ┣━━━━╋━━━━━━╋━━━━━━╋━━━━━━╋━━━━━━┫
    ┃ A1 ┃ 0.90 ┃ 0.85 ┃ 0.45 ┃ 0.96 ┃
    ┣━━━━╋━━━━━━╋━━━━━━╋━━━━━━╋━━━━━━┫
    ┃ B1 ┃      ┃ 0.90 ┃ 0.85 ┃ 0.56 ┃
    ┣━━━━╋━━━━━━╋━━━━━━╋━━━━━━╋━━━━━━┫
    ┃ C1 ┃      ┃      ┃ 0.55 ┃ 0.45 ┃
    ┣━━━━╋━━━━━━╋━━━━━━╋━━━━━━╋━━━━━━┫
    ┃ D1 ┃      ┃      ┃      ┃ 0.90 ┃
    ┗━━━━┻━━━━━━┻━━━━━━┻━━━━━━┻━━━━━━┛

Another example: Shuffled columns:

    $ csvtk cut -f 1,4,2,3 testdata/names.csv \
      | csvtk pretty -S simple
    ----------------------------------------
    id   username   first_name   last_name
    ----------------------------------------
    11   rob        Rob          Pike
    2    ken        Ken          Thompson
    4    gri        Robert       Griesemer
    1    abc        Robert       Thompson
    NA   123        Robert       Abel
    ----------------------------------------

data -> gather/longer ->  spread/wider. Note that the orders of both rows and columns are kept :)

    $ csvtk cut -f 1,4,2,3 testdata/names.csv \
        | csvtk gather -k item -v value -f -1 \
        | csvtk spread -k item -v value \
        | csvtk pretty -S simple
    ----------------------------------------
    id   username   first_name   last_name
    ----------------------------------------
    11   rob        Rob          Pike
    2    ken        Ken          Thompson
    4    gri        Robert       Griesemer
    1    abc        Robert       Thompson
    NA   123        Robert       Abel
    ----------------------------------------

**Comment by shenwei356** [comment]
Added two new commands, which should be more straightforward.

      - `csvtk long2matrix`: convert the long format to a matrix.
      - `csvtk matrix2long`: convert a matrix to the long format.


## long2matrix

Usage

```text
convert a long format to a matrix

Input: a three-column table. E.g.,

    col1   col2   value    
    A      A      1868883.0
    A      B      1310746.0
    B      A      1306936.0
    B      B      2117177.0

Output: a matrix with the same column and row names. E.g.,

        A           B        
    A   1868883.0   1310746.0
    B   1306936.0   2117177.0

Usage:
  csvtk long2matrix [flags] 

Flags:
  -B, --clear-bad-value     keep records failing to pass the filter but clear the value
  -f, --fields strings      the three fields/column to use. e.g., -f 1,2,3 or -f a,b,v (default [1-3])
  -h, --help                help for long2matrix
  -N, --keep-non-numberic   keep non-numeric values when filter by --min-value or --max-value
  -M, --max-value float     only save records with values <= this value (default 1.7976931348623157e+308)
  -m, --min-value float     only save records with values >= this value (default -1.7976931348623157e+308)
      --na string           content for filling NA data

```

Examles

```
$ cat testdata/pairwise-data.tsv 
A1      A1      0.90
A1      B1      0.85
A1      C1      0.45
A1      D1      0.96
B1      B1      0.90
B1      C1      0.85
B1      D1      0.56
C1      C1      0.55
C1      D1      0.45
D1      D1      0.90

# all data
$ cat testdata/pairwise-data.tsv | csvtk long2matrix -Ht \
  | csvtk pretty -t -S round
╭────┬──────┬──────┬──────┬──────╮
│    │ A1   │ B1   │ C1   │ D1   │
├────┼──────┼──────┼──────┼──────┤
│ A1 │ 0.90 │ 0.85 │ 0.45 │ 0.96 │
├────┼──────┼──────┼──────┼──────┤
│ B1 │      │ 0.90 │ 0.85 │ 0.56 │
├────┼──────┼──────┼──────┼──────┤
│ C1 │      │      │ 0.55 │ 0.45 │
├────┼──────┼──────┼──────┼──────┤
│ D1 │      │      │      │ 0.90 │
╰────┴──────┴──────┴──────┴──────╯

# keep records failing to pass the filter but clear the value
$ cat testdata/pairwise-data.tsv | csvtk long2matrix -t --min-value 0.9 --na . \
  | csvtk pretty -t -S round
╭────┬────┬──────┬──────╮
│    │ A1 │ B1   │ D1   │
├────┼────┼──────┼──────┤
│ A1 │ .  │ .    │ 0.96 │
├────┼────┼──────┼──────┤
│ B1 │ .  │ 0.90 │ .    │
├────┼────┼──────┼──────┤
│ D1 │ .  │ .    │ 0.90 │
╰────┴────┴──────┴──────╯

# keep records even for those failed to pass the filter
$ cat testdata/pairwise-data.tsv | csvtk long2matrix -t --min-value 0.9 --clear-bad-value \
  | csvtk pretty -t -S round
╭────┬────┬──────┬────┬──────╮
│    │ A1 │ B1   │ C1 │ D1   │
├────┼────┼──────┼────┼──────┤
│ A1 │    │      │    │ 0.96 │
├────┼────┼──────┼────┼──────┤
│ B1 │    │ 0.90 │    │      │
├────┼────┼──────┼────┼──────┤
│ C1 │    │      │    │      │
├────┼────┼──────┼────┼──────┤
│ D1 │    │      │    │ 0.90 │
╰────┴────┴──────┴────┴──────╯

```

## matrix2long

Usage

```text
convert a matrix to the long format

Input: a matrix with the same column and row names. E.g.,

        A           B        
    A   1868883.0   1310746.0
    B   1306936.0   2117177.0

Output: a three-column table. E.g.,

    col1   col2   value    
    A      A      1868883.0
    A      B      1310746.0
    B      A      1306936.0
    B      B      2117177.0

Usage:
  csvtk matrix2long [flags] 

Flags:
  -B, --blanks strings      blank values, case ignored (default [,na,n/a,none,null,.])
  -n, --colnames strings    column names of the output (3 values required). e.g -n a,b,v (default
                            [col1,col2,value])
  -h, --help                help for matrix2long
  -N, --keep-non-numberic   keep non-numeric values when filter by --min-value or --max-value
  -M, --max-value float     only show records with values <= this value (default 1.7976931348623157e+308)
  -m, --min-value float     only show records with values >= this value (default -1.7976931348623157e+308)
  -b, --skip-blanks         skip records with blank values (defined by --blanks)
  -s, --skip-same-keys      skip records with the same key names
```

Examples

```
# data
$ cat testdata/pairwise-data.matrix.tsv | csvtk pretty -t -S round
╭────┬──────┬──────┬──────┬──────╮
│    │ A1   │ B1   │ C1   │ D1   │
├────┼──────┼──────┼──────┼──────┤
│ A1 │ 0.90 │ 0.85 │ 0.45 │ 0.96 │
├────┼──────┼──────┼──────┼──────┤
│ B1 │      │ 0.90 │ 0.85 │ 0.56 │
├────┼──────┼──────┼──────┼──────┤
│ C1 │      │      │ 0.55 │ 0.45 │
├────┼──────┼──────┼──────┼──────┤
│ D1 │      │      │      │ 0.90 │
╰────┴──────┴──────┴──────┴──────╯

# remove records without values
$ cat testdata/pairwise-data.matrix.tsv \
  | csvtk matrix2long -t --skip-blanks
col1    col2    value
A1      A1      0.90
A1      B1      0.85
A1      C1      0.45
A1      D1      0.96
B1      B1      0.90
B1      C1      0.85
B1      D1      0.56
C1      C1      0.55
C1      D1      0.45
D1      D1      0.90

# and filter values, and remove the header line
$ cat testdata/pairwise-data.matrix.tsv \
  | csvtk matrix2long -t --skip-blanks --min-value 0.9 --delete-header
A1      A1      0.90
A1      D1      0.96
B1      B1      0.90
D1      D1      0.90
```

**Comment by shenwei356** [comment]
Please try the binaries here: #371
