### ISSUE TITLE
tab2csv no header by default

### ISSUE THREAD

**Issue by cchurchw** [shenwei356/csvtk#92]
I like csvkt, it's a useful quick tool for handling csv files. However, I had difficultly converting tab delimited files to CSVs using tab2csv command. Every time it cuts the header off the file without passing -H flag. Below is an example of the code I'm using. Minor issue.

```bash
cat O_final_files_for_r/chp_16s_mapping.txt | csvtk tab2csv  > O_final_files_for_r/chp_16s_mapping2.csv
```

csvtk version 0.19.1
source Bioconda
CentOS Linux release 7.6.1810 (Core)

**Comment by shenwei356** [comment]
> By default, lines starting with # will be ignored, if the header row starts with #, please assign flag -C another rare symbol, e.g. '$'.

**Comment by cchurchw** [comment]
Thanks for the quick answer. That did solve the issue, as you guessed my header did start with #
I couldn't initially get the -C flag to work, but got it working by adding empty quotes and letting it  default to #

```bash
cat chp_16s_mapping.txt | csvtk tab2csv -C > chp_16s_mapping.csv
# fails - requires comment character

cat chp_16s_mapping.txt | csvtk tab2csv -C '#' > chp_16s_mapping.csv
# header still missing

cat chp_16s_mapping.txt | csvtk tab2csv -C '' > chp_16s_mapping.csv
# works
```
Thanks again

**Comment by shenwei356** [comment]
```
Global Flags:
  -C, --comment-char string    lines starting with commment-character will be ignored. if your header row starts with '#', please assign "-C" another rare symbol, e.g. '$' (default "#")

```
