### ISSUE TITLE
SQL queries on data

### ISSUE THREAD

**Issue by geekscrapy** [shenwei356/csvtk#94]
Any chance of an additional sub command to allow SQL queries on the data? Much like csvkit does?

Great tool! Thanks

**Comment by shenwei356** [comment]
Sorry, there's no plan recently.

**Comment by avilella** [comment]
What I've done in the past is to pipe the results of csvtk into
http://harelba.github.io/q/ for this purpose.

**Comment by geekscrapy** [comment]
Thanks @avilella - I was looking for something a little faster than a python script. Haven't tested it yet with timings, but this works well - Creates an in memory sql db:

cat file.csv | sqlite3  -header -csv -separator ',' "file::memory" '.import /dev/stdin t' 'select * from t'

**Comment by avilella** [comment]
Neat! I like it!
