### ISSUE TITLE
Cannot transition token types from VARIABLE [window_start_coordinate] to STRING [_]

### ISSUE THREAD

**Issue by lakhujanivijay** [shenwei356/csvtk#95]
I have a CSV table like this

chromosome|window_start_coordinate|window_end_coordinate|DEL_or_DUP
:---------|:----------------------|:--------------------|:---------
1         |1396129                |1398088              |DUP
1         |1647784                |1647917              |DUP
1         |2420645                |2431159              |DUP

and I want to create a new column say `cnv_identifier` with the concatenation of all these columns; something like this :

```1_1396129_1398088_DUP
    1_1647784_1647917_DUP
    1_2420645_2431159_DUP
```

My command is 
```
csvtk mutate2 -t -n cnv_identifier -e '$chromosome + "_" + $window_start_coordinate "_" + $window_end_coordinate + "_" $DEL_or_DUP'
```
I got this error:

`[ERRO] Cannot transition token types from VARIABLE [window_start_coordinate] to STRING [_]`

Note: my table has headers

**Comment by shenwei356** [comment]
You miss some '+':
```
$ cat t.txt \
    | csvtk mutate2 -s  -t -n cnv_identifier \
        -e '$chromosome + "_" + $window_start_coordinate + "_" + $window_end_coordinate + "_" + $DEL_or_DUP'
```
and you should use 

    -s, --digits-as-string    treate digits as string to avoid converting big digits into scientific notation

**Comment by lakhujanivijay** [comment]
Ugh, thanks for pointing that out https://github.com/shenwei356 
 :+1:
