### ISSUE TITLE
Is there a way to know which rows are causing trouble?

### ISSUE THREAD

**Issue by matrs** [shenwei356/csvtk#97]
Hello, first, thank for this program, it's really useful.

I'm using `csvtk v0.19.1`

When doing:
```bash
$  csvtk -I dim file.tsv
 file.tsv: 95 illegal rows ignored
```
Is there a way to know those lines?  My guess is that for the program to report them should be easy because it's already detecting them. I think that  an option to show those lines' number in the output can be very useful and maybe some info about the number of fields too.

What do you think?

**Comment by shenwei356** [comment]
```
$ csvtk -I dim file.tsv
[WARN] file '-': 2 illegal rows ignored: [2 4]
```
Here's the pre-release: 
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4154321/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4154323/csvtk_linux_amd64.tar.gz)

**Comment by matrs** [comment]
Thank you!
