### ISSUE TITLE
csvtk concat even if only one file

### ISSUE THREAD

**Issue by avilella** [shenwei356/csvtk#98]
Feature request:

I find myself writing reporting bash scripts that find files to then `csvtk concat`. Sometimes I kick off the reporting bash script even when only one of the files is available, and then instead of concatenating the single file to the next step in the bash pipe, I get the `csvtk concat` error:
```
[ERRO] at least 2 files needed
```

Would it be possible to add a flag to `csvtk concat` that, when enabled, proceeds with the concatenation even if only one file is found? Or maybe there is a bash if/else that can be applied here with not much typing. Thanks in advance.

**Comment by shenwei356** [comment]
It's solved by just removing the file count restriction. 

-  [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4213858/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4213856/csvtk_darwin_amd64.tar.gz)

This scenario is quiet common, in my another project. I shouldn't have limited the files.
