### ISSUE TITLE
join lists --ignore-case as parameter but does not support it

### ISSUE THREAD

**Issue by tolot27** [shenwei356/csvtk#99]
Parameter `-i, --ignore-case` is printed by `csvtk join --help` but in https://github.com/shenwei356/csvtk/blob/master/csvtk/cmd/join.go#L62 it is commented and not used anymore. Hence, field content with different case do not match, regardless of the use of `-i`.

Example: `csvtk join -t -i -k <(echo -e "A\tball\nb\tcircle") <(echo -e "A\tis round\nB\tis flat")` produces:

```
A	ball	is round
b	circle
```

instead of:

```
A	ball	is round
b	circle	is flat
```

**Comment by shenwei356** [comment]
Sorry, I don't remember when and why it's commented. 

- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/4355240/csvtk_windows_amd64.exe.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4355237/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/4355232/csvtk_darwin_amd64.tar.gz)
